// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"gokeep/server/internal/ent/backuprecord"
	"gokeep/server/internal/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BackupRecordQuery is the builder for querying BackupRecord entities.
type BackupRecordQuery struct {
	config
	ctx        *QueryContext
	order      []backuprecord.OrderOption
	inters     []Interceptor
	predicates []predicate.BackupRecord
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BackupRecordQuery builder.
func (brq *BackupRecordQuery) Where(ps ...predicate.BackupRecord) *BackupRecordQuery {
	brq.predicates = append(brq.predicates, ps...)
	return brq
}

// Limit the number of records to be returned by this query.
func (brq *BackupRecordQuery) Limit(limit int) *BackupRecordQuery {
	brq.ctx.Limit = &limit
	return brq
}

// Offset to start from.
func (brq *BackupRecordQuery) Offset(offset int) *BackupRecordQuery {
	brq.ctx.Offset = &offset
	return brq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (brq *BackupRecordQuery) Unique(unique bool) *BackupRecordQuery {
	brq.ctx.Unique = &unique
	return brq
}

// Order specifies how the records should be ordered.
func (brq *BackupRecordQuery) Order(o ...backuprecord.OrderOption) *BackupRecordQuery {
	brq.order = append(brq.order, o...)
	return brq
}

// First returns the first BackupRecord entity from the query.
// Returns a *NotFoundError when no BackupRecord was found.
func (brq *BackupRecordQuery) First(ctx context.Context) (*BackupRecord, error) {
	nodes, err := brq.Limit(1).All(setContextOp(ctx, brq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{backuprecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (brq *BackupRecordQuery) FirstX(ctx context.Context) *BackupRecord {
	node, err := brq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BackupRecord ID from the query.
// Returns a *NotFoundError when no BackupRecord ID was found.
func (brq *BackupRecordQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = brq.Limit(1).IDs(setContextOp(ctx, brq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{backuprecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (brq *BackupRecordQuery) FirstIDX(ctx context.Context) int64 {
	id, err := brq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BackupRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BackupRecord entity is found.
// Returns a *NotFoundError when no BackupRecord entities are found.
func (brq *BackupRecordQuery) Only(ctx context.Context) (*BackupRecord, error) {
	nodes, err := brq.Limit(2).All(setContextOp(ctx, brq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{backuprecord.Label}
	default:
		return nil, &NotSingularError{backuprecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (brq *BackupRecordQuery) OnlyX(ctx context.Context) *BackupRecord {
	node, err := brq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BackupRecord ID in the query.
// Returns a *NotSingularError when more than one BackupRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (brq *BackupRecordQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = brq.Limit(2).IDs(setContextOp(ctx, brq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{backuprecord.Label}
	default:
		err = &NotSingularError{backuprecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (brq *BackupRecordQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := brq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BackupRecords.
func (brq *BackupRecordQuery) All(ctx context.Context) ([]*BackupRecord, error) {
	ctx = setContextOp(ctx, brq.ctx, ent.OpQueryAll)
	if err := brq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BackupRecord, *BackupRecordQuery]()
	return withInterceptors[[]*BackupRecord](ctx, brq, qr, brq.inters)
}

// AllX is like All, but panics if an error occurs.
func (brq *BackupRecordQuery) AllX(ctx context.Context) []*BackupRecord {
	nodes, err := brq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BackupRecord IDs.
func (brq *BackupRecordQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if brq.ctx.Unique == nil && brq.path != nil {
		brq.Unique(true)
	}
	ctx = setContextOp(ctx, brq.ctx, ent.OpQueryIDs)
	if err = brq.Select(backuprecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (brq *BackupRecordQuery) IDsX(ctx context.Context) []int64 {
	ids, err := brq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (brq *BackupRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, brq.ctx, ent.OpQueryCount)
	if err := brq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, brq, querierCount[*BackupRecordQuery](), brq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (brq *BackupRecordQuery) CountX(ctx context.Context) int {
	count, err := brq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (brq *BackupRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, brq.ctx, ent.OpQueryExist)
	switch _, err := brq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (brq *BackupRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := brq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BackupRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (brq *BackupRecordQuery) Clone() *BackupRecordQuery {
	if brq == nil {
		return nil
	}
	return &BackupRecordQuery{
		config:     brq.config,
		ctx:        brq.ctx.Clone(),
		order:      append([]backuprecord.OrderOption{}, brq.order...),
		inters:     append([]Interceptor{}, brq.inters...),
		predicates: append([]predicate.BackupRecord{}, brq.predicates...),
		// clone intermediate query.
		sql:  brq.sql.Clone(),
		path: brq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedBy string `json:"created_by,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BackupRecord.Query().
//		GroupBy(backuprecord.FieldCreatedBy).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (brq *BackupRecordQuery) GroupBy(field string, fields ...string) *BackupRecordGroupBy {
	brq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BackupRecordGroupBy{build: brq}
	grbuild.flds = &brq.ctx.Fields
	grbuild.label = backuprecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedBy string `json:"created_by,omitempty"`
//	}
//
//	client.BackupRecord.Query().
//		Select(backuprecord.FieldCreatedBy).
//		Scan(ctx, &v)
func (brq *BackupRecordQuery) Select(fields ...string) *BackupRecordSelect {
	brq.ctx.Fields = append(brq.ctx.Fields, fields...)
	sbuild := &BackupRecordSelect{BackupRecordQuery: brq}
	sbuild.label = backuprecord.Label
	sbuild.flds, sbuild.scan = &brq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BackupRecordSelect configured with the given aggregations.
func (brq *BackupRecordQuery) Aggregate(fns ...AggregateFunc) *BackupRecordSelect {
	return brq.Select().Aggregate(fns...)
}

func (brq *BackupRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range brq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, brq); err != nil {
				return err
			}
		}
	}
	for _, f := range brq.ctx.Fields {
		if !backuprecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if brq.path != nil {
		prev, err := brq.path(ctx)
		if err != nil {
			return err
		}
		brq.sql = prev
	}
	return nil
}

func (brq *BackupRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BackupRecord, error) {
	var (
		nodes = []*BackupRecord{}
		_spec = brq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BackupRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BackupRecord{config: brq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, brq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (brq *BackupRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := brq.querySpec()
	_spec.Node.Columns = brq.ctx.Fields
	if len(brq.ctx.Fields) > 0 {
		_spec.Unique = brq.ctx.Unique != nil && *brq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, brq.driver, _spec)
}

func (brq *BackupRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(backuprecord.Table, backuprecord.Columns, sqlgraph.NewFieldSpec(backuprecord.FieldID, field.TypeInt64))
	_spec.From = brq.sql
	if unique := brq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if brq.path != nil {
		_spec.Unique = true
	}
	if fields := brq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backuprecord.FieldID)
		for i := range fields {
			if fields[i] != backuprecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := brq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := brq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := brq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := brq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (brq *BackupRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(brq.driver.Dialect())
	t1 := builder.Table(backuprecord.Table)
	columns := brq.ctx.Fields
	if len(columns) == 0 {
		columns = backuprecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if brq.sql != nil {
		selector = brq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if brq.ctx.Unique != nil && *brq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range brq.predicates {
		p(selector)
	}
	for _, p := range brq.order {
		p(selector)
	}
	if offset := brq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := brq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BackupRecordGroupBy is the group-by builder for BackupRecord entities.
type BackupRecordGroupBy struct {
	selector
	build *BackupRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (brgb *BackupRecordGroupBy) Aggregate(fns ...AggregateFunc) *BackupRecordGroupBy {
	brgb.fns = append(brgb.fns, fns...)
	return brgb
}

// Scan applies the selector query and scans the result into the given value.
func (brgb *BackupRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, brgb.build.ctx, ent.OpQueryGroupBy)
	if err := brgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BackupRecordQuery, *BackupRecordGroupBy](ctx, brgb.build, brgb, brgb.build.inters, v)
}

func (brgb *BackupRecordGroupBy) sqlScan(ctx context.Context, root *BackupRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(brgb.fns))
	for _, fn := range brgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*brgb.flds)+len(brgb.fns))
		for _, f := range *brgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*brgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := brgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BackupRecordSelect is the builder for selecting fields of BackupRecord entities.
type BackupRecordSelect struct {
	*BackupRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (brs *BackupRecordSelect) Aggregate(fns ...AggregateFunc) *BackupRecordSelect {
	brs.fns = append(brs.fns, fns...)
	return brs
}

// Scan applies the selector query and scans the result into the given value.
func (brs *BackupRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, brs.ctx, ent.OpQuerySelect)
	if err := brs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BackupRecordQuery, *BackupRecordSelect](ctx, brs.BackupRecordQuery, brs, brs.inters, v)
}

func (brs *BackupRecordSelect) sqlScan(ctx context.Context, root *BackupRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(brs.fns))
	for _, fn := range brs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*brs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := brs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
