// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gokeep/server/internal/ent/backuprecord"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BackupRecord is the model entity for the BackupRecord schema.
type BackupRecord struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID int64 `json:"id,omitempty"`
	// 创建者
	CreatedBy string `json:"created_by,omitempty"`
	// 更新者
	UpdatedBy string `json:"updated_by,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 软删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 备份记录短ID（8位hex）
	RecordKey string `json:"record_key,omitempty"`
	// 状态 running/completed/failed
	Status string `json:"status,omitempty"`
	// 备份文件名（S3 key）
	FileName string `json:"file_name,omitempty"`
	// 文件大小（字节）
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// 分卷数
	Parts int `json:"parts,omitempty"`
	// 过期时间（过期天数换算，0天=空）
	ExpireAt *time.Time `json:"expire_at,omitempty"`
	// 触发方式 manual 手动 / scheduled 定时
	TriggerType string `json:"trigger_type,omitempty"`
	// 开始时间
	StartedAt time.Time `json:"started_at,omitempty"`
	// 完成时间
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// 失败原因
	ErrorMessage *string `json:"error_message,omitempty"`
	// 耗时(毫秒)
	DurationMs   float64 `json:"duration_ms,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BackupRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case backuprecord.FieldDurationMs:
			values[i] = new(sql.NullFloat64)
		case backuprecord.FieldID, backuprecord.FieldSizeBytes, backuprecord.FieldParts:
			values[i] = new(sql.NullInt64)
		case backuprecord.FieldCreatedBy, backuprecord.FieldUpdatedBy, backuprecord.FieldRecordKey, backuprecord.FieldStatus, backuprecord.FieldFileName, backuprecord.FieldTriggerType, backuprecord.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case backuprecord.FieldCreatedAt, backuprecord.FieldUpdatedAt, backuprecord.FieldDeletedAt, backuprecord.FieldExpireAt, backuprecord.FieldStartedAt, backuprecord.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BackupRecord fields.
func (br *BackupRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case backuprecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			br.ID = int64(value.Int64)
		case backuprecord.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				br.CreatedBy = value.String
			}
		case backuprecord.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				br.UpdatedBy = value.String
			}
		case backuprecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				br.CreatedAt = value.Time
			}
		case backuprecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				br.UpdatedAt = value.Time
			}
		case backuprecord.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				br.DeletedAt = new(time.Time)
				*br.DeletedAt = value.Time
			}
		case backuprecord.FieldRecordKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field record_key", values[i])
			} else if value.Valid {
				br.RecordKey = value.String
			}
		case backuprecord.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				br.Status = value.String
			}
		case backuprecord.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				br.FileName = value.String
			}
		case backuprecord.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				br.SizeBytes = value.Int64
			}
		case backuprecord.FieldParts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parts", values[i])
			} else if value.Valid {
				br.Parts = int(value.Int64)
			}
		case backuprecord.FieldExpireAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expire_at", values[i])
			} else if value.Valid {
				br.ExpireAt = new(time.Time)
				*br.ExpireAt = value.Time
			}
		case backuprecord.FieldTriggerType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_type", values[i])
			} else if value.Valid {
				br.TriggerType = value.String
			}
		case backuprecord.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				br.StartedAt = value.Time
			}
		case backuprecord.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				br.FinishedAt = new(time.Time)
				*br.FinishedAt = value.Time
			}
		case backuprecord.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				br.ErrorMessage = new(string)
				*br.ErrorMessage = value.String
			}
		case backuprecord.FieldDurationMs:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				br.DurationMs = value.Float64
			}
		default:
			br.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BackupRecord.
// This includes values selected through modifiers, order, etc.
func (br *BackupRecord) Value(name string) (ent.Value, error) {
	return br.selectValues.Get(name)
}

// Update returns a builder for updating this BackupRecord.
// Note that you need to call BackupRecord.Unwrap() before calling this method if this BackupRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (br *BackupRecord) Update() *BackupRecordUpdateOne {
	return NewBackupRecordClient(br.config).UpdateOne(br)
}

// Unwrap unwraps the BackupRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (br *BackupRecord) Unwrap() *BackupRecord {
	_tx, ok := br.config.driver.(*txDriver)
	if !ok {
		panic("ent: BackupRecord is not a transactional entity")
	}
	br.config.driver = _tx.drv
	return br
}

// String implements the fmt.Stringer.
func (br *BackupRecord) String() string {
	var builder strings.Builder
	builder.WriteString("BackupRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", br.ID))
	builder.WriteString("created_by=")
	builder.WriteString(br.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(br.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(br.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(br.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := br.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("record_key=")
	builder.WriteString(br.RecordKey)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(br.Status)
	builder.WriteString(", ")
	builder.WriteString("file_name=")
	builder.WriteString(br.FileName)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", br.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("parts=")
	builder.WriteString(fmt.Sprintf("%v", br.Parts))
	builder.WriteString(", ")
	if v := br.ExpireAt; v != nil {
		builder.WriteString("expire_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("trigger_type=")
	builder.WriteString(br.TriggerType)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(br.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := br.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := br.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", br.DurationMs))
	builder.WriteByte(')')
	return builder.String()
}

// BackupRecords is a parsable slice of BackupRecord.
type BackupRecords []*BackupRecord
