// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gokeep/server/internal/ent/backuprecord"
	"gokeep/server/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BackupRecordUpdate is the builder for updating BackupRecord entities.
type BackupRecordUpdate struct {
	config
	hooks    []Hook
	mutation *BackupRecordMutation
}

// Where appends a list predicates to the BackupRecordUpdate builder.
func (bru *BackupRecordUpdate) Where(ps ...predicate.BackupRecord) *BackupRecordUpdate {
	bru.mutation.Where(ps...)
	return bru
}

// SetCreatedBy sets the "created_by" field.
func (bru *BackupRecordUpdate) SetCreatedBy(s string) *BackupRecordUpdate {
	bru.mutation.SetCreatedBy(s)
	return bru
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (bru *BackupRecordUpdate) SetNillableCreatedBy(s *string) *BackupRecordUpdate {
	if s != nil {
		bru.SetCreatedBy(*s)
	}
	return bru
}

// SetUpdatedBy sets the "updated_by" field.
func (bru *BackupRecordUpdate) SetUpdatedBy(s string) *BackupRecordUpdate {
	bru.mutation.SetUpdatedBy(s)
	return bru
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (bru *BackupRecordUpdate) SetNillableUpdatedBy(s *string) *BackupRecordUpdate {
	if s != nil {
		bru.SetUpdatedBy(*s)
	}
	return bru
}

// SetUpdatedAt sets the "updated_at" field.
func (bru *BackupRecordUpdate) SetUpdatedAt(t time.Time) *BackupRecordUpdate {
	bru.mutation.SetUpdatedAt(t)
	return bru
}

// SetDeletedAt sets the "deleted_at" field.
func (bru *BackupRecordUpdate) SetDeletedAt(t time.Time) *BackupRecordUpdate {
	bru.mutation.SetDeletedAt(t)
	return bru
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (bru *BackupRecordUpdate) SetNillableDeletedAt(t *time.Time) *BackupRecordUpdate {
	if t != nil {
		bru.SetDeletedAt(*t)
	}
	return bru
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (bru *BackupRecordUpdate) ClearDeletedAt() *BackupRecordUpdate {
	bru.mutation.ClearDeletedAt()
	return bru
}

// SetRecordKey sets the "record_key" field.
func (bru *BackupRecordUpdate) SetRecordKey(s string) *BackupRecordUpdate {
	bru.mutation.SetRecordKey(s)
	return bru
}

// SetNillableRecordKey sets the "record_key" field if the given value is not nil.
func (bru *BackupRecordUpdate) SetNillableRecordKey(s *string) *BackupRecordUpdate {
	if s != nil {
		bru.SetRecordKey(*s)
	}
	return bru
}

// SetStatus sets the "status" field.
func (bru *BackupRecordUpdate) SetStatus(s string) *BackupRecordUpdate {
	bru.mutation.SetStatus(s)
	return bru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (bru *BackupRecordUpdate) SetNillableStatus(s *string) *BackupRecordUpdate {
	if s != nil {
		bru.SetStatus(*s)
	}
	return bru
}

// SetFileName sets the "file_name" field.
func (bru *BackupRecordUpdate) SetFileName(s string) *BackupRecordUpdate {
	bru.mutation.SetFileName(s)
	return bru
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (bru *BackupRecordUpdate) SetNillableFileName(s *string) *BackupRecordUpdate {
	if s != nil {
		bru.SetFileName(*s)
	}
	return bru
}

// SetSizeBytes sets the "size_bytes" field.
func (bru *BackupRecordUpdate) SetSizeBytes(i int64) *BackupRecordUpdate {
	bru.mutation.ResetSizeBytes()
	bru.mutation.SetSizeBytes(i)
	return bru
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (bru *BackupRecordUpdate) SetNillableSizeBytes(i *int64) *BackupRecordUpdate {
	if i != nil {
		bru.SetSizeBytes(*i)
	}
	return bru
}

// AddSizeBytes adds i to the "size_bytes" field.
func (bru *BackupRecordUpdate) AddSizeBytes(i int64) *BackupRecordUpdate {
	bru.mutation.AddSizeBytes(i)
	return bru
}

// SetParts sets the "parts" field.
func (bru *BackupRecordUpdate) SetParts(i int) *BackupRecordUpdate {
	bru.mutation.ResetParts()
	bru.mutation.SetParts(i)
	return bru
}

// SetNillableParts sets the "parts" field if the given value is not nil.
func (bru *BackupRecordUpdate) SetNillableParts(i *int) *BackupRecordUpdate {
	if i != nil {
		bru.SetParts(*i)
	}
	return bru
}

// AddParts adds i to the "parts" field.
func (bru *BackupRecordUpdate) AddParts(i int) *BackupRecordUpdate {
	bru.mutation.AddParts(i)
	return bru
}

// SetExpireAt sets the "expire_at" field.
func (bru *BackupRecordUpdate) SetExpireAt(t time.Time) *BackupRecordUpdate {
	bru.mutation.SetExpireAt(t)
	return bru
}

// SetNillableExpireAt sets the "expire_at" field if the given value is not nil.
func (bru *BackupRecordUpdate) SetNillableExpireAt(t *time.Time) *BackupRecordUpdate {
	if t != nil {
		bru.SetExpireAt(*t)
	}
	return bru
}

// ClearExpireAt clears the value of the "expire_at" field.
func (bru *BackupRecordUpdate) ClearExpireAt() *BackupRecordUpdate {
	bru.mutation.ClearExpireAt()
	return bru
}

// SetTriggerType sets the "trigger_type" field.
func (bru *BackupRecordUpdate) SetTriggerType(s string) *BackupRecordUpdate {
	bru.mutation.SetTriggerType(s)
	return bru
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (bru *BackupRecordUpdate) SetNillableTriggerType(s *string) *BackupRecordUpdate {
	if s != nil {
		bru.SetTriggerType(*s)
	}
	return bru
}

// SetStartedAt sets the "started_at" field.
func (bru *BackupRecordUpdate) SetStartedAt(t time.Time) *BackupRecordUpdate {
	bru.mutation.SetStartedAt(t)
	return bru
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (bru *BackupRecordUpdate) SetNillableStartedAt(t *time.Time) *BackupRecordUpdate {
	if t != nil {
		bru.SetStartedAt(*t)
	}
	return bru
}

// SetFinishedAt sets the "finished_at" field.
func (bru *BackupRecordUpdate) SetFinishedAt(t time.Time) *BackupRecordUpdate {
	bru.mutation.SetFinishedAt(t)
	return bru
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (bru *BackupRecordUpdate) SetNillableFinishedAt(t *time.Time) *BackupRecordUpdate {
	if t != nil {
		bru.SetFinishedAt(*t)
	}
	return bru
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (bru *BackupRecordUpdate) ClearFinishedAt() *BackupRecordUpdate {
	bru.mutation.ClearFinishedAt()
	return bru
}

// SetErrorMessage sets the "error_message" field.
func (bru *BackupRecordUpdate) SetErrorMessage(s string) *BackupRecordUpdate {
	bru.mutation.SetErrorMessage(s)
	return bru
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (bru *BackupRecordUpdate) SetNillableErrorMessage(s *string) *BackupRecordUpdate {
	if s != nil {
		bru.SetErrorMessage(*s)
	}
	return bru
}

// ClearErrorMessage clears the value of the "error_message" field.
func (bru *BackupRecordUpdate) ClearErrorMessage() *BackupRecordUpdate {
	bru.mutation.ClearErrorMessage()
	return bru
}

// SetDurationMs sets the "duration_ms" field.
func (bru *BackupRecordUpdate) SetDurationMs(f float64) *BackupRecordUpdate {
	bru.mutation.ResetDurationMs()
	bru.mutation.SetDurationMs(f)
	return bru
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (bru *BackupRecordUpdate) SetNillableDurationMs(f *float64) *BackupRecordUpdate {
	if f != nil {
		bru.SetDurationMs(*f)
	}
	return bru
}

// AddDurationMs adds f to the "duration_ms" field.
func (bru *BackupRecordUpdate) AddDurationMs(f float64) *BackupRecordUpdate {
	bru.mutation.AddDurationMs(f)
	return bru
}

// Mutation returns the BackupRecordMutation object of the builder.
func (bru *BackupRecordUpdate) Mutation() *BackupRecordMutation {
	return bru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bru *BackupRecordUpdate) Save(ctx context.Context) (int, error) {
	bru.defaults()
	return withHooks(ctx, bru.sqlSave, bru.mutation, bru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bru *BackupRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := bru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bru *BackupRecordUpdate) Exec(ctx context.Context) error {
	_, err := bru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bru *BackupRecordUpdate) ExecX(ctx context.Context) {
	if err := bru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bru *BackupRecordUpdate) defaults() {
	if _, ok := bru.mutation.UpdatedAt(); !ok {
		v := backuprecord.UpdateDefaultUpdatedAt()
		bru.mutation.SetUpdatedAt(v)
	}
}

func (bru *BackupRecordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(backuprecord.Table, backuprecord.Columns, sqlgraph.NewFieldSpec(backuprecord.FieldID, field.TypeInt64))
	if ps := bru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bru.mutation.CreatedBy(); ok {
		_spec.SetField(backuprecord.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := bru.mutation.UpdatedBy(); ok {
		_spec.SetField(backuprecord.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := bru.mutation.UpdatedAt(); ok {
		_spec.SetField(backuprecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := bru.mutation.DeletedAt(); ok {
		_spec.SetField(backuprecord.FieldDeletedAt, field.TypeTime, value)
	}
	if bru.mutation.DeletedAtCleared() {
		_spec.ClearField(backuprecord.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := bru.mutation.RecordKey(); ok {
		_spec.SetField(backuprecord.FieldRecordKey, field.TypeString, value)
	}
	if value, ok := bru.mutation.Status(); ok {
		_spec.SetField(backuprecord.FieldStatus, field.TypeString, value)
	}
	if value, ok := bru.mutation.FileName(); ok {
		_spec.SetField(backuprecord.FieldFileName, field.TypeString, value)
	}
	if value, ok := bru.mutation.SizeBytes(); ok {
		_spec.SetField(backuprecord.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := bru.mutation.AddedSizeBytes(); ok {
		_spec.AddField(backuprecord.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := bru.mutation.Parts(); ok {
		_spec.SetField(backuprecord.FieldParts, field.TypeInt, value)
	}
	if value, ok := bru.mutation.AddedParts(); ok {
		_spec.AddField(backuprecord.FieldParts, field.TypeInt, value)
	}
	if value, ok := bru.mutation.ExpireAt(); ok {
		_spec.SetField(backuprecord.FieldExpireAt, field.TypeTime, value)
	}
	if bru.mutation.ExpireAtCleared() {
		_spec.ClearField(backuprecord.FieldExpireAt, field.TypeTime)
	}
	if value, ok := bru.mutation.TriggerType(); ok {
		_spec.SetField(backuprecord.FieldTriggerType, field.TypeString, value)
	}
	if value, ok := bru.mutation.StartedAt(); ok {
		_spec.SetField(backuprecord.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := bru.mutation.FinishedAt(); ok {
		_spec.SetField(backuprecord.FieldFinishedAt, field.TypeTime, value)
	}
	if bru.mutation.FinishedAtCleared() {
		_spec.ClearField(backuprecord.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := bru.mutation.ErrorMessage(); ok {
		_spec.SetField(backuprecord.FieldErrorMessage, field.TypeString, value)
	}
	if bru.mutation.ErrorMessageCleared() {
		_spec.ClearField(backuprecord.FieldErrorMessage, field.TypeString)
	}
	if value, ok := bru.mutation.DurationMs(); ok {
		_spec.SetField(backuprecord.FieldDurationMs, field.TypeFloat64, value)
	}
	if value, ok := bru.mutation.AddedDurationMs(); ok {
		_spec.AddField(backuprecord.FieldDurationMs, field.TypeFloat64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backuprecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bru.mutation.done = true
	return n, nil
}

// BackupRecordUpdateOne is the builder for updating a single BackupRecord entity.
type BackupRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BackupRecordMutation
}

// SetCreatedBy sets the "created_by" field.
func (bruo *BackupRecordUpdateOne) SetCreatedBy(s string) *BackupRecordUpdateOne {
	bruo.mutation.SetCreatedBy(s)
	return bruo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (bruo *BackupRecordUpdateOne) SetNillableCreatedBy(s *string) *BackupRecordUpdateOne {
	if s != nil {
		bruo.SetCreatedBy(*s)
	}
	return bruo
}

// SetUpdatedBy sets the "updated_by" field.
func (bruo *BackupRecordUpdateOne) SetUpdatedBy(s string) *BackupRecordUpdateOne {
	bruo.mutation.SetUpdatedBy(s)
	return bruo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (bruo *BackupRecordUpdateOne) SetNillableUpdatedBy(s *string) *BackupRecordUpdateOne {
	if s != nil {
		bruo.SetUpdatedBy(*s)
	}
	return bruo
}

// SetUpdatedAt sets the "updated_at" field.
func (bruo *BackupRecordUpdateOne) SetUpdatedAt(t time.Time) *BackupRecordUpdateOne {
	bruo.mutation.SetUpdatedAt(t)
	return bruo
}

// SetDeletedAt sets the "deleted_at" field.
func (bruo *BackupRecordUpdateOne) SetDeletedAt(t time.Time) *BackupRecordUpdateOne {
	bruo.mutation.SetDeletedAt(t)
	return bruo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (bruo *BackupRecordUpdateOne) SetNillableDeletedAt(t *time.Time) *BackupRecordUpdateOne {
	if t != nil {
		bruo.SetDeletedAt(*t)
	}
	return bruo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (bruo *BackupRecordUpdateOne) ClearDeletedAt() *BackupRecordUpdateOne {
	bruo.mutation.ClearDeletedAt()
	return bruo
}

// SetRecordKey sets the "record_key" field.
func (bruo *BackupRecordUpdateOne) SetRecordKey(s string) *BackupRecordUpdateOne {
	bruo.mutation.SetRecordKey(s)
	return bruo
}

// SetNillableRecordKey sets the "record_key" field if the given value is not nil.
func (bruo *BackupRecordUpdateOne) SetNillableRecordKey(s *string) *BackupRecordUpdateOne {
	if s != nil {
		bruo.SetRecordKey(*s)
	}
	return bruo
}

// SetStatus sets the "status" field.
func (bruo *BackupRecordUpdateOne) SetStatus(s string) *BackupRecordUpdateOne {
	bruo.mutation.SetStatus(s)
	return bruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (bruo *BackupRecordUpdateOne) SetNillableStatus(s *string) *BackupRecordUpdateOne {
	if s != nil {
		bruo.SetStatus(*s)
	}
	return bruo
}

// SetFileName sets the "file_name" field.
func (bruo *BackupRecordUpdateOne) SetFileName(s string) *BackupRecordUpdateOne {
	bruo.mutation.SetFileName(s)
	return bruo
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (bruo *BackupRecordUpdateOne) SetNillableFileName(s *string) *BackupRecordUpdateOne {
	if s != nil {
		bruo.SetFileName(*s)
	}
	return bruo
}

// SetSizeBytes sets the "size_bytes" field.
func (bruo *BackupRecordUpdateOne) SetSizeBytes(i int64) *BackupRecordUpdateOne {
	bruo.mutation.ResetSizeBytes()
	bruo.mutation.SetSizeBytes(i)
	return bruo
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (bruo *BackupRecordUpdateOne) SetNillableSizeBytes(i *int64) *BackupRecordUpdateOne {
	if i != nil {
		bruo.SetSizeBytes(*i)
	}
	return bruo
}

// AddSizeBytes adds i to the "size_bytes" field.
func (bruo *BackupRecordUpdateOne) AddSizeBytes(i int64) *BackupRecordUpdateOne {
	bruo.mutation.AddSizeBytes(i)
	return bruo
}

// SetParts sets the "parts" field.
func (bruo *BackupRecordUpdateOne) SetParts(i int) *BackupRecordUpdateOne {
	bruo.mutation.ResetParts()
	bruo.mutation.SetParts(i)
	return bruo
}

// SetNillableParts sets the "parts" field if the given value is not nil.
func (bruo *BackupRecordUpdateOne) SetNillableParts(i *int) *BackupRecordUpdateOne {
	if i != nil {
		bruo.SetParts(*i)
	}
	return bruo
}

// AddParts adds i to the "parts" field.
func (bruo *BackupRecordUpdateOne) AddParts(i int) *BackupRecordUpdateOne {
	bruo.mutation.AddParts(i)
	return bruo
}

// SetExpireAt sets the "expire_at" field.
func (bruo *BackupRecordUpdateOne) SetExpireAt(t time.Time) *BackupRecordUpdateOne {
	bruo.mutation.SetExpireAt(t)
	return bruo
}

// SetNillableExpireAt sets the "expire_at" field if the given value is not nil.
func (bruo *BackupRecordUpdateOne) SetNillableExpireAt(t *time.Time) *BackupRecordUpdateOne {
	if t != nil {
		bruo.SetExpireAt(*t)
	}
	return bruo
}

// ClearExpireAt clears the value of the "expire_at" field.
func (bruo *BackupRecordUpdateOne) ClearExpireAt() *BackupRecordUpdateOne {
	bruo.mutation.ClearExpireAt()
	return bruo
}

// SetTriggerType sets the "trigger_type" field.
func (bruo *BackupRecordUpdateOne) SetTriggerType(s string) *BackupRecordUpdateOne {
	bruo.mutation.SetTriggerType(s)
	return bruo
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (bruo *BackupRecordUpdateOne) SetNillableTriggerType(s *string) *BackupRecordUpdateOne {
	if s != nil {
		bruo.SetTriggerType(*s)
	}
	return bruo
}

// SetStartedAt sets the "started_at" field.
func (bruo *BackupRecordUpdateOne) SetStartedAt(t time.Time) *BackupRecordUpdateOne {
	bruo.mutation.SetStartedAt(t)
	return bruo
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (bruo *BackupRecordUpdateOne) SetNillableStartedAt(t *time.Time) *BackupRecordUpdateOne {
	if t != nil {
		bruo.SetStartedAt(*t)
	}
	return bruo
}

// SetFinishedAt sets the "finished_at" field.
func (bruo *BackupRecordUpdateOne) SetFinishedAt(t time.Time) *BackupRecordUpdateOne {
	bruo.mutation.SetFinishedAt(t)
	return bruo
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (bruo *BackupRecordUpdateOne) SetNillableFinishedAt(t *time.Time) *BackupRecordUpdateOne {
	if t != nil {
		bruo.SetFinishedAt(*t)
	}
	return bruo
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (bruo *BackupRecordUpdateOne) ClearFinishedAt() *BackupRecordUpdateOne {
	bruo.mutation.ClearFinishedAt()
	return bruo
}

// SetErrorMessage sets the "error_message" field.
func (bruo *BackupRecordUpdateOne) SetErrorMessage(s string) *BackupRecordUpdateOne {
	bruo.mutation.SetErrorMessage(s)
	return bruo
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (bruo *BackupRecordUpdateOne) SetNillableErrorMessage(s *string) *BackupRecordUpdateOne {
	if s != nil {
		bruo.SetErrorMessage(*s)
	}
	return bruo
}

// ClearErrorMessage clears the value of the "error_message" field.
func (bruo *BackupRecordUpdateOne) ClearErrorMessage() *BackupRecordUpdateOne {
	bruo.mutation.ClearErrorMessage()
	return bruo
}

// SetDurationMs sets the "duration_ms" field.
func (bruo *BackupRecordUpdateOne) SetDurationMs(f float64) *BackupRecordUpdateOne {
	bruo.mutation.ResetDurationMs()
	bruo.mutation.SetDurationMs(f)
	return bruo
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (bruo *BackupRecordUpdateOne) SetNillableDurationMs(f *float64) *BackupRecordUpdateOne {
	if f != nil {
		bruo.SetDurationMs(*f)
	}
	return bruo
}

// AddDurationMs adds f to the "duration_ms" field.
func (bruo *BackupRecordUpdateOne) AddDurationMs(f float64) *BackupRecordUpdateOne {
	bruo.mutation.AddDurationMs(f)
	return bruo
}

// Mutation returns the BackupRecordMutation object of the builder.
func (bruo *BackupRecordUpdateOne) Mutation() *BackupRecordMutation {
	return bruo.mutation
}

// Where appends a list predicates to the BackupRecordUpdate builder.
func (bruo *BackupRecordUpdateOne) Where(ps ...predicate.BackupRecord) *BackupRecordUpdateOne {
	bruo.mutation.Where(ps...)
	return bruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (bruo *BackupRecordUpdateOne) Select(field string, fields ...string) *BackupRecordUpdateOne {
	bruo.fields = append([]string{field}, fields...)
	return bruo
}

// Save executes the query and returns the updated BackupRecord entity.
func (bruo *BackupRecordUpdateOne) Save(ctx context.Context) (*BackupRecord, error) {
	bruo.defaults()
	return withHooks(ctx, bruo.sqlSave, bruo.mutation, bruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bruo *BackupRecordUpdateOne) SaveX(ctx context.Context) *BackupRecord {
	node, err := bruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (bruo *BackupRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := bruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bruo *BackupRecordUpdateOne) ExecX(ctx context.Context) {
	if err := bruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bruo *BackupRecordUpdateOne) defaults() {
	if _, ok := bruo.mutation.UpdatedAt(); !ok {
		v := backuprecord.UpdateDefaultUpdatedAt()
		bruo.mutation.SetUpdatedAt(v)
	}
}

func (bruo *BackupRecordUpdateOne) sqlSave(ctx context.Context) (_node *BackupRecord, err error) {
	_spec := sqlgraph.NewUpdateSpec(backuprecord.Table, backuprecord.Columns, sqlgraph.NewFieldSpec(backuprecord.FieldID, field.TypeInt64))
	id, ok := bruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BackupRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := bruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backuprecord.FieldID)
		for _, f := range fields {
			if !backuprecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backuprecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := bruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bruo.mutation.CreatedBy(); ok {
		_spec.SetField(backuprecord.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := bruo.mutation.UpdatedBy(); ok {
		_spec.SetField(backuprecord.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := bruo.mutation.UpdatedAt(); ok {
		_spec.SetField(backuprecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := bruo.mutation.DeletedAt(); ok {
		_spec.SetField(backuprecord.FieldDeletedAt, field.TypeTime, value)
	}
	if bruo.mutation.DeletedAtCleared() {
		_spec.ClearField(backuprecord.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := bruo.mutation.RecordKey(); ok {
		_spec.SetField(backuprecord.FieldRecordKey, field.TypeString, value)
	}
	if value, ok := bruo.mutation.Status(); ok {
		_spec.SetField(backuprecord.FieldStatus, field.TypeString, value)
	}
	if value, ok := bruo.mutation.FileName(); ok {
		_spec.SetField(backuprecord.FieldFileName, field.TypeString, value)
	}
	if value, ok := bruo.mutation.SizeBytes(); ok {
		_spec.SetField(backuprecord.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := bruo.mutation.AddedSizeBytes(); ok {
		_spec.AddField(backuprecord.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := bruo.mutation.Parts(); ok {
		_spec.SetField(backuprecord.FieldParts, field.TypeInt, value)
	}
	if value, ok := bruo.mutation.AddedParts(); ok {
		_spec.AddField(backuprecord.FieldParts, field.TypeInt, value)
	}
	if value, ok := bruo.mutation.ExpireAt(); ok {
		_spec.SetField(backuprecord.FieldExpireAt, field.TypeTime, value)
	}
	if bruo.mutation.ExpireAtCleared() {
		_spec.ClearField(backuprecord.FieldExpireAt, field.TypeTime)
	}
	if value, ok := bruo.mutation.TriggerType(); ok {
		_spec.SetField(backuprecord.FieldTriggerType, field.TypeString, value)
	}
	if value, ok := bruo.mutation.StartedAt(); ok {
		_spec.SetField(backuprecord.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := bruo.mutation.FinishedAt(); ok {
		_spec.SetField(backuprecord.FieldFinishedAt, field.TypeTime, value)
	}
	if bruo.mutation.FinishedAtCleared() {
		_spec.ClearField(backuprecord.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := bruo.mutation.ErrorMessage(); ok {
		_spec.SetField(backuprecord.FieldErrorMessage, field.TypeString, value)
	}
	if bruo.mutation.ErrorMessageCleared() {
		_spec.ClearField(backuprecord.FieldErrorMessage, field.TypeString)
	}
	if value, ok := bruo.mutation.DurationMs(); ok {
		_spec.SetField(backuprecord.FieldDurationMs, field.TypeFloat64, value)
	}
	if value, ok := bruo.mutation.AddedDurationMs(); ok {
		_spec.AddField(backuprecord.FieldDurationMs, field.TypeFloat64, value)
	}
	_node = &BackupRecord{config: bruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, bruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backuprecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	bruo.mutation.done = true
	return _node, nil
}
