// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gokeep/server/internal/ent/predicate"
	"gokeep/server/internal/ent/sysconfig"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysConfigUpdate is the builder for updating SysConfig entities.
type SysConfigUpdate struct {
	config
	hooks    []Hook
	mutation *SysConfigMutation
}

// Where appends a list predicates to the SysConfigUpdate builder.
func (scu *SysConfigUpdate) Where(ps ...predicate.SysConfig) *SysConfigUpdate {
	scu.mutation.Where(ps...)
	return scu
}

// SetCreatedBy sets the "created_by" field.
func (scu *SysConfigUpdate) SetCreatedBy(s string) *SysConfigUpdate {
	scu.mutation.SetCreatedBy(s)
	return scu
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (scu *SysConfigUpdate) SetNillableCreatedBy(s *string) *SysConfigUpdate {
	if s != nil {
		scu.SetCreatedBy(*s)
	}
	return scu
}

// SetUpdatedBy sets the "updated_by" field.
func (scu *SysConfigUpdate) SetUpdatedBy(s string) *SysConfigUpdate {
	scu.mutation.SetUpdatedBy(s)
	return scu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (scu *SysConfigUpdate) SetNillableUpdatedBy(s *string) *SysConfigUpdate {
	if s != nil {
		scu.SetUpdatedBy(*s)
	}
	return scu
}

// SetUpdatedAt sets the "updated_at" field.
func (scu *SysConfigUpdate) SetUpdatedAt(t time.Time) *SysConfigUpdate {
	scu.mutation.SetUpdatedAt(t)
	return scu
}

// SetDeletedAt sets the "deleted_at" field.
func (scu *SysConfigUpdate) SetDeletedAt(t time.Time) *SysConfigUpdate {
	scu.mutation.SetDeletedAt(t)
	return scu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (scu *SysConfigUpdate) SetNillableDeletedAt(t *time.Time) *SysConfigUpdate {
	if t != nil {
		scu.SetDeletedAt(*t)
	}
	return scu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (scu *SysConfigUpdate) ClearDeletedAt() *SysConfigUpdate {
	scu.mutation.ClearDeletedAt()
	return scu
}

// SetName sets the "name" field.
func (scu *SysConfigUpdate) SetName(s string) *SysConfigUpdate {
	scu.mutation.SetName(s)
	return scu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (scu *SysConfigUpdate) SetNillableName(s *string) *SysConfigUpdate {
	if s != nil {
		scu.SetName(*s)
	}
	return scu
}

// SetKey sets the "key" field.
func (scu *SysConfigUpdate) SetKey(s string) *SysConfigUpdate {
	scu.mutation.SetKey(s)
	return scu
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (scu *SysConfigUpdate) SetNillableKey(s *string) *SysConfigUpdate {
	if s != nil {
		scu.SetKey(*s)
	}
	return scu
}

// SetValue sets the "value" field.
func (scu *SysConfigUpdate) SetValue(s string) *SysConfigUpdate {
	scu.mutation.SetValue(s)
	return scu
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (scu *SysConfigUpdate) SetNillableValue(s *string) *SysConfigUpdate {
	if s != nil {
		scu.SetValue(*s)
	}
	return scu
}

// SetRemark sets the "remark" field.
func (scu *SysConfigUpdate) SetRemark(s string) *SysConfigUpdate {
	scu.mutation.SetRemark(s)
	return scu
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (scu *SysConfigUpdate) SetNillableRemark(s *string) *SysConfigUpdate {
	if s != nil {
		scu.SetRemark(*s)
	}
	return scu
}

// ClearRemark clears the value of the "remark" field.
func (scu *SysConfigUpdate) ClearRemark() *SysConfigUpdate {
	scu.mutation.ClearRemark()
	return scu
}

// Mutation returns the SysConfigMutation object of the builder.
func (scu *SysConfigUpdate) Mutation() *SysConfigMutation {
	return scu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (scu *SysConfigUpdate) Save(ctx context.Context) (int, error) {
	scu.defaults()
	return withHooks(ctx, scu.sqlSave, scu.mutation, scu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (scu *SysConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := scu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (scu *SysConfigUpdate) Exec(ctx context.Context) error {
	_, err := scu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scu *SysConfigUpdate) ExecX(ctx context.Context) {
	if err := scu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (scu *SysConfigUpdate) defaults() {
	if _, ok := scu.mutation.UpdatedAt(); !ok {
		v := sysconfig.UpdateDefaultUpdatedAt()
		scu.mutation.SetUpdatedAt(v)
	}
}

func (scu *SysConfigUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysconfig.Table, sysconfig.Columns, sqlgraph.NewFieldSpec(sysconfig.FieldID, field.TypeInt64))
	if ps := scu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := scu.mutation.CreatedBy(); ok {
		_spec.SetField(sysconfig.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := scu.mutation.UpdatedBy(); ok {
		_spec.SetField(sysconfig.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := scu.mutation.UpdatedAt(); ok {
		_spec.SetField(sysconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := scu.mutation.DeletedAt(); ok {
		_spec.SetField(sysconfig.FieldDeletedAt, field.TypeTime, value)
	}
	if scu.mutation.DeletedAtCleared() {
		_spec.ClearField(sysconfig.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := scu.mutation.Name(); ok {
		_spec.SetField(sysconfig.FieldName, field.TypeString, value)
	}
	if value, ok := scu.mutation.Key(); ok {
		_spec.SetField(sysconfig.FieldKey, field.TypeString, value)
	}
	if value, ok := scu.mutation.Value(); ok {
		_spec.SetField(sysconfig.FieldValue, field.TypeString, value)
	}
	if value, ok := scu.mutation.Remark(); ok {
		_spec.SetField(sysconfig.FieldRemark, field.TypeString, value)
	}
	if scu.mutation.RemarkCleared() {
		_spec.ClearField(sysconfig.FieldRemark, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, scu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	scu.mutation.done = true
	return n, nil
}

// SysConfigUpdateOne is the builder for updating a single SysConfig entity.
type SysConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysConfigMutation
}

// SetCreatedBy sets the "created_by" field.
func (scuo *SysConfigUpdateOne) SetCreatedBy(s string) *SysConfigUpdateOne {
	scuo.mutation.SetCreatedBy(s)
	return scuo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (scuo *SysConfigUpdateOne) SetNillableCreatedBy(s *string) *SysConfigUpdateOne {
	if s != nil {
		scuo.SetCreatedBy(*s)
	}
	return scuo
}

// SetUpdatedBy sets the "updated_by" field.
func (scuo *SysConfigUpdateOne) SetUpdatedBy(s string) *SysConfigUpdateOne {
	scuo.mutation.SetUpdatedBy(s)
	return scuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (scuo *SysConfigUpdateOne) SetNillableUpdatedBy(s *string) *SysConfigUpdateOne {
	if s != nil {
		scuo.SetUpdatedBy(*s)
	}
	return scuo
}

// SetUpdatedAt sets the "updated_at" field.
func (scuo *SysConfigUpdateOne) SetUpdatedAt(t time.Time) *SysConfigUpdateOne {
	scuo.mutation.SetUpdatedAt(t)
	return scuo
}

// SetDeletedAt sets the "deleted_at" field.
func (scuo *SysConfigUpdateOne) SetDeletedAt(t time.Time) *SysConfigUpdateOne {
	scuo.mutation.SetDeletedAt(t)
	return scuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (scuo *SysConfigUpdateOne) SetNillableDeletedAt(t *time.Time) *SysConfigUpdateOne {
	if t != nil {
		scuo.SetDeletedAt(*t)
	}
	return scuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (scuo *SysConfigUpdateOne) ClearDeletedAt() *SysConfigUpdateOne {
	scuo.mutation.ClearDeletedAt()
	return scuo
}

// SetName sets the "name" field.
func (scuo *SysConfigUpdateOne) SetName(s string) *SysConfigUpdateOne {
	scuo.mutation.SetName(s)
	return scuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (scuo *SysConfigUpdateOne) SetNillableName(s *string) *SysConfigUpdateOne {
	if s != nil {
		scuo.SetName(*s)
	}
	return scuo
}

// SetKey sets the "key" field.
func (scuo *SysConfigUpdateOne) SetKey(s string) *SysConfigUpdateOne {
	scuo.mutation.SetKey(s)
	return scuo
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (scuo *SysConfigUpdateOne) SetNillableKey(s *string) *SysConfigUpdateOne {
	if s != nil {
		scuo.SetKey(*s)
	}
	return scuo
}

// SetValue sets the "value" field.
func (scuo *SysConfigUpdateOne) SetValue(s string) *SysConfigUpdateOne {
	scuo.mutation.SetValue(s)
	return scuo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (scuo *SysConfigUpdateOne) SetNillableValue(s *string) *SysConfigUpdateOne {
	if s != nil {
		scuo.SetValue(*s)
	}
	return scuo
}

// SetRemark sets the "remark" field.
func (scuo *SysConfigUpdateOne) SetRemark(s string) *SysConfigUpdateOne {
	scuo.mutation.SetRemark(s)
	return scuo
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (scuo *SysConfigUpdateOne) SetNillableRemark(s *string) *SysConfigUpdateOne {
	if s != nil {
		scuo.SetRemark(*s)
	}
	return scuo
}

// ClearRemark clears the value of the "remark" field.
func (scuo *SysConfigUpdateOne) ClearRemark() *SysConfigUpdateOne {
	scuo.mutation.ClearRemark()
	return scuo
}

// Mutation returns the SysConfigMutation object of the builder.
func (scuo *SysConfigUpdateOne) Mutation() *SysConfigMutation {
	return scuo.mutation
}

// Where appends a list predicates to the SysConfigUpdate builder.
func (scuo *SysConfigUpdateOne) Where(ps ...predicate.SysConfig) *SysConfigUpdateOne {
	scuo.mutation.Where(ps...)
	return scuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (scuo *SysConfigUpdateOne) Select(field string, fields ...string) *SysConfigUpdateOne {
	scuo.fields = append([]string{field}, fields...)
	return scuo
}

// Save executes the query and returns the updated SysConfig entity.
func (scuo *SysConfigUpdateOne) Save(ctx context.Context) (*SysConfig, error) {
	scuo.defaults()
	return withHooks(ctx, scuo.sqlSave, scuo.mutation, scuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (scuo *SysConfigUpdateOne) SaveX(ctx context.Context) *SysConfig {
	node, err := scuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (scuo *SysConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := scuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scuo *SysConfigUpdateOne) ExecX(ctx context.Context) {
	if err := scuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (scuo *SysConfigUpdateOne) defaults() {
	if _, ok := scuo.mutation.UpdatedAt(); !ok {
		v := sysconfig.UpdateDefaultUpdatedAt()
		scuo.mutation.SetUpdatedAt(v)
	}
}

func (scuo *SysConfigUpdateOne) sqlSave(ctx context.Context) (_node *SysConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysconfig.Table, sysconfig.Columns, sqlgraph.NewFieldSpec(sysconfig.FieldID, field.TypeInt64))
	id, ok := scuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := scuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysconfig.FieldID)
		for _, f := range fields {
			if !sysconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := scuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := scuo.mutation.CreatedBy(); ok {
		_spec.SetField(sysconfig.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := scuo.mutation.UpdatedBy(); ok {
		_spec.SetField(sysconfig.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := scuo.mutation.UpdatedAt(); ok {
		_spec.SetField(sysconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := scuo.mutation.DeletedAt(); ok {
		_spec.SetField(sysconfig.FieldDeletedAt, field.TypeTime, value)
	}
	if scuo.mutation.DeletedAtCleared() {
		_spec.ClearField(sysconfig.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := scuo.mutation.Name(); ok {
		_spec.SetField(sysconfig.FieldName, field.TypeString, value)
	}
	if value, ok := scuo.mutation.Key(); ok {
		_spec.SetField(sysconfig.FieldKey, field.TypeString, value)
	}
	if value, ok := scuo.mutation.Value(); ok {
		_spec.SetField(sysconfig.FieldValue, field.TypeString, value)
	}
	if value, ok := scuo.mutation.Remark(); ok {
		_spec.SetField(sysconfig.FieldRemark, field.TypeString, value)
	}
	if scuo.mutation.RemarkCleared() {
		_spec.ClearField(sysconfig.FieldRemark, field.TypeString)
	}
	_node = &SysConfig{config: scuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, scuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	scuo.mutation.done = true
	return _node, nil
}
