// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gokeep/server/internal/ent/sysdictdata"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysDictDataCreate is the builder for creating a SysDictData entity.
type SysDictDataCreate struct {
	config
	mutation *SysDictDataMutation
	hooks    []Hook
}

// SetCreatedBy sets the "created_by" field.
func (sddc *SysDictDataCreate) SetCreatedBy(s string) *SysDictDataCreate {
	sddc.mutation.SetCreatedBy(s)
	return sddc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (sddc *SysDictDataCreate) SetNillableCreatedBy(s *string) *SysDictDataCreate {
	if s != nil {
		sddc.SetCreatedBy(*s)
	}
	return sddc
}

// SetUpdatedBy sets the "updated_by" field.
func (sddc *SysDictDataCreate) SetUpdatedBy(s string) *SysDictDataCreate {
	sddc.mutation.SetUpdatedBy(s)
	return sddc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (sddc *SysDictDataCreate) SetNillableUpdatedBy(s *string) *SysDictDataCreate {
	if s != nil {
		sddc.SetUpdatedBy(*s)
	}
	return sddc
}

// SetCreatedAt sets the "created_at" field.
func (sddc *SysDictDataCreate) SetCreatedAt(t time.Time) *SysDictDataCreate {
	sddc.mutation.SetCreatedAt(t)
	return sddc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sddc *SysDictDataCreate) SetNillableCreatedAt(t *time.Time) *SysDictDataCreate {
	if t != nil {
		sddc.SetCreatedAt(*t)
	}
	return sddc
}

// SetUpdatedAt sets the "updated_at" field.
func (sddc *SysDictDataCreate) SetUpdatedAt(t time.Time) *SysDictDataCreate {
	sddc.mutation.SetUpdatedAt(t)
	return sddc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sddc *SysDictDataCreate) SetNillableUpdatedAt(t *time.Time) *SysDictDataCreate {
	if t != nil {
		sddc.SetUpdatedAt(*t)
	}
	return sddc
}

// SetDeletedAt sets the "deleted_at" field.
func (sddc *SysDictDataCreate) SetDeletedAt(t time.Time) *SysDictDataCreate {
	sddc.mutation.SetDeletedAt(t)
	return sddc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sddc *SysDictDataCreate) SetNillableDeletedAt(t *time.Time) *SysDictDataCreate {
	if t != nil {
		sddc.SetDeletedAt(*t)
	}
	return sddc
}

// SetSort sets the "sort" field.
func (sddc *SysDictDataCreate) SetSort(i int) *SysDictDataCreate {
	sddc.mutation.SetSort(i)
	return sddc
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (sddc *SysDictDataCreate) SetNillableSort(i *int) *SysDictDataCreate {
	if i != nil {
		sddc.SetSort(*i)
	}
	return sddc
}

// SetLabel sets the "label" field.
func (sddc *SysDictDataCreate) SetLabel(s string) *SysDictDataCreate {
	sddc.mutation.SetLabel(s)
	return sddc
}

// SetValue sets the "value" field.
func (sddc *SysDictDataCreate) SetValue(s string) *SysDictDataCreate {
	sddc.mutation.SetValue(s)
	return sddc
}

// SetDictType sets the "dict_type" field.
func (sddc *SysDictDataCreate) SetDictType(s string) *SysDictDataCreate {
	sddc.mutation.SetDictType(s)
	return sddc
}

// SetStatus sets the "status" field.
func (sddc *SysDictDataCreate) SetStatus(s string) *SysDictDataCreate {
	sddc.mutation.SetStatus(s)
	return sddc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sddc *SysDictDataCreate) SetNillableStatus(s *string) *SysDictDataCreate {
	if s != nil {
		sddc.SetStatus(*s)
	}
	return sddc
}

// SetRemark sets the "remark" field.
func (sddc *SysDictDataCreate) SetRemark(s string) *SysDictDataCreate {
	sddc.mutation.SetRemark(s)
	return sddc
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (sddc *SysDictDataCreate) SetNillableRemark(s *string) *SysDictDataCreate {
	if s != nil {
		sddc.SetRemark(*s)
	}
	return sddc
}

// SetID sets the "id" field.
func (sddc *SysDictDataCreate) SetID(i int64) *SysDictDataCreate {
	sddc.mutation.SetID(i)
	return sddc
}

// Mutation returns the SysDictDataMutation object of the builder.
func (sddc *SysDictDataCreate) Mutation() *SysDictDataMutation {
	return sddc.mutation
}

// Save creates the SysDictData in the database.
func (sddc *SysDictDataCreate) Save(ctx context.Context) (*SysDictData, error) {
	sddc.defaults()
	return withHooks(ctx, sddc.sqlSave, sddc.mutation, sddc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sddc *SysDictDataCreate) SaveX(ctx context.Context) *SysDictData {
	v, err := sddc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sddc *SysDictDataCreate) Exec(ctx context.Context) error {
	_, err := sddc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sddc *SysDictDataCreate) ExecX(ctx context.Context) {
	if err := sddc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sddc *SysDictDataCreate) defaults() {
	if _, ok := sddc.mutation.CreatedBy(); !ok {
		v := sysdictdata.DefaultCreatedBy
		sddc.mutation.SetCreatedBy(v)
	}
	if _, ok := sddc.mutation.UpdatedBy(); !ok {
		v := sysdictdata.DefaultUpdatedBy
		sddc.mutation.SetUpdatedBy(v)
	}
	if _, ok := sddc.mutation.CreatedAt(); !ok {
		v := sysdictdata.DefaultCreatedAt()
		sddc.mutation.SetCreatedAt(v)
	}
	if _, ok := sddc.mutation.UpdatedAt(); !ok {
		v := sysdictdata.DefaultUpdatedAt()
		sddc.mutation.SetUpdatedAt(v)
	}
	if _, ok := sddc.mutation.Sort(); !ok {
		v := sysdictdata.DefaultSort
		sddc.mutation.SetSort(v)
	}
	if _, ok := sddc.mutation.Status(); !ok {
		v := sysdictdata.DefaultStatus
		sddc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sddc *SysDictDataCreate) check() error {
	if _, ok := sddc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "SysDictData.created_by"`)}
	}
	if _, ok := sddc.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "SysDictData.updated_by"`)}
	}
	if _, ok := sddc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysDictData.created_at"`)}
	}
	if _, ok := sddc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SysDictData.updated_at"`)}
	}
	if _, ok := sddc.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "SysDictData.sort"`)}
	}
	if _, ok := sddc.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "SysDictData.label"`)}
	}
	if _, ok := sddc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "SysDictData.value"`)}
	}
	if _, ok := sddc.mutation.DictType(); !ok {
		return &ValidationError{Name: "dict_type", err: errors.New(`ent: missing required field "SysDictData.dict_type"`)}
	}
	if _, ok := sddc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SysDictData.status"`)}
	}
	return nil
}

func (sddc *SysDictDataCreate) sqlSave(ctx context.Context) (*SysDictData, error) {
	if err := sddc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sddc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sddc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	sddc.mutation.id = &_node.ID
	sddc.mutation.done = true
	return _node, nil
}

func (sddc *SysDictDataCreate) createSpec() (*SysDictData, *sqlgraph.CreateSpec) {
	var (
		_node = &SysDictData{config: sddc.config}
		_spec = sqlgraph.NewCreateSpec(sysdictdata.Table, sqlgraph.NewFieldSpec(sysdictdata.FieldID, field.TypeInt64))
	)
	if id, ok := sddc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sddc.mutation.CreatedBy(); ok {
		_spec.SetField(sysdictdata.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := sddc.mutation.UpdatedBy(); ok {
		_spec.SetField(sysdictdata.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := sddc.mutation.CreatedAt(); ok {
		_spec.SetField(sysdictdata.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sddc.mutation.UpdatedAt(); ok {
		_spec.SetField(sysdictdata.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sddc.mutation.DeletedAt(); ok {
		_spec.SetField(sysdictdata.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := sddc.mutation.Sort(); ok {
		_spec.SetField(sysdictdata.FieldSort, field.TypeInt, value)
		_node.Sort = value
	}
	if value, ok := sddc.mutation.Label(); ok {
		_spec.SetField(sysdictdata.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := sddc.mutation.Value(); ok {
		_spec.SetField(sysdictdata.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := sddc.mutation.DictType(); ok {
		_spec.SetField(sysdictdata.FieldDictType, field.TypeString, value)
		_node.DictType = value
	}
	if value, ok := sddc.mutation.Status(); ok {
		_spec.SetField(sysdictdata.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := sddc.mutation.Remark(); ok {
		_spec.SetField(sysdictdata.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	return _node, _spec
}

// SysDictDataCreateBulk is the builder for creating many SysDictData entities in bulk.
type SysDictDataCreateBulk struct {
	config
	err      error
	builders []*SysDictDataCreate
}

// Save creates the SysDictData entities in the database.
func (sddcb *SysDictDataCreateBulk) Save(ctx context.Context) ([]*SysDictData, error) {
	if sddcb.err != nil {
		return nil, sddcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sddcb.builders))
	nodes := make([]*SysDictData, len(sddcb.builders))
	mutators := make([]Mutator, len(sddcb.builders))
	for i := range sddcb.builders {
		func(i int, root context.Context) {
			builder := sddcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysDictDataMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sddcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sddcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sddcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sddcb *SysDictDataCreateBulk) SaveX(ctx context.Context) []*SysDictData {
	v, err := sddcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sddcb *SysDictDataCreateBulk) Exec(ctx context.Context) error {
	_, err := sddcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sddcb *SysDictDataCreateBulk) ExecX(ctx context.Context) {
	if err := sddcb.Exec(ctx); err != nil {
		panic(err)
	}
}
