// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gokeep/server/internal/ent/sysdicttype"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysDictTypeCreate is the builder for creating a SysDictType entity.
type SysDictTypeCreate struct {
	config
	mutation *SysDictTypeMutation
	hooks    []Hook
}

// SetCreatedBy sets the "created_by" field.
func (sdtc *SysDictTypeCreate) SetCreatedBy(s string) *SysDictTypeCreate {
	sdtc.mutation.SetCreatedBy(s)
	return sdtc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (sdtc *SysDictTypeCreate) SetNillableCreatedBy(s *string) *SysDictTypeCreate {
	if s != nil {
		sdtc.SetCreatedBy(*s)
	}
	return sdtc
}

// SetUpdatedBy sets the "updated_by" field.
func (sdtc *SysDictTypeCreate) SetUpdatedBy(s string) *SysDictTypeCreate {
	sdtc.mutation.SetUpdatedBy(s)
	return sdtc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (sdtc *SysDictTypeCreate) SetNillableUpdatedBy(s *string) *SysDictTypeCreate {
	if s != nil {
		sdtc.SetUpdatedBy(*s)
	}
	return sdtc
}

// SetCreatedAt sets the "created_at" field.
func (sdtc *SysDictTypeCreate) SetCreatedAt(t time.Time) *SysDictTypeCreate {
	sdtc.mutation.SetCreatedAt(t)
	return sdtc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sdtc *SysDictTypeCreate) SetNillableCreatedAt(t *time.Time) *SysDictTypeCreate {
	if t != nil {
		sdtc.SetCreatedAt(*t)
	}
	return sdtc
}

// SetUpdatedAt sets the "updated_at" field.
func (sdtc *SysDictTypeCreate) SetUpdatedAt(t time.Time) *SysDictTypeCreate {
	sdtc.mutation.SetUpdatedAt(t)
	return sdtc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sdtc *SysDictTypeCreate) SetNillableUpdatedAt(t *time.Time) *SysDictTypeCreate {
	if t != nil {
		sdtc.SetUpdatedAt(*t)
	}
	return sdtc
}

// SetDeletedAt sets the "deleted_at" field.
func (sdtc *SysDictTypeCreate) SetDeletedAt(t time.Time) *SysDictTypeCreate {
	sdtc.mutation.SetDeletedAt(t)
	return sdtc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sdtc *SysDictTypeCreate) SetNillableDeletedAt(t *time.Time) *SysDictTypeCreate {
	if t != nil {
		sdtc.SetDeletedAt(*t)
	}
	return sdtc
}

// SetName sets the "name" field.
func (sdtc *SysDictTypeCreate) SetName(s string) *SysDictTypeCreate {
	sdtc.mutation.SetName(s)
	return sdtc
}

// SetType sets the "type" field.
func (sdtc *SysDictTypeCreate) SetType(s string) *SysDictTypeCreate {
	sdtc.mutation.SetType(s)
	return sdtc
}

// SetStatus sets the "status" field.
func (sdtc *SysDictTypeCreate) SetStatus(s string) *SysDictTypeCreate {
	sdtc.mutation.SetStatus(s)
	return sdtc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sdtc *SysDictTypeCreate) SetNillableStatus(s *string) *SysDictTypeCreate {
	if s != nil {
		sdtc.SetStatus(*s)
	}
	return sdtc
}

// SetRemark sets the "remark" field.
func (sdtc *SysDictTypeCreate) SetRemark(s string) *SysDictTypeCreate {
	sdtc.mutation.SetRemark(s)
	return sdtc
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (sdtc *SysDictTypeCreate) SetNillableRemark(s *string) *SysDictTypeCreate {
	if s != nil {
		sdtc.SetRemark(*s)
	}
	return sdtc
}

// SetID sets the "id" field.
func (sdtc *SysDictTypeCreate) SetID(i int64) *SysDictTypeCreate {
	sdtc.mutation.SetID(i)
	return sdtc
}

// Mutation returns the SysDictTypeMutation object of the builder.
func (sdtc *SysDictTypeCreate) Mutation() *SysDictTypeMutation {
	return sdtc.mutation
}

// Save creates the SysDictType in the database.
func (sdtc *SysDictTypeCreate) Save(ctx context.Context) (*SysDictType, error) {
	sdtc.defaults()
	return withHooks(ctx, sdtc.sqlSave, sdtc.mutation, sdtc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sdtc *SysDictTypeCreate) SaveX(ctx context.Context) *SysDictType {
	v, err := sdtc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sdtc *SysDictTypeCreate) Exec(ctx context.Context) error {
	_, err := sdtc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sdtc *SysDictTypeCreate) ExecX(ctx context.Context) {
	if err := sdtc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sdtc *SysDictTypeCreate) defaults() {
	if _, ok := sdtc.mutation.CreatedBy(); !ok {
		v := sysdicttype.DefaultCreatedBy
		sdtc.mutation.SetCreatedBy(v)
	}
	if _, ok := sdtc.mutation.UpdatedBy(); !ok {
		v := sysdicttype.DefaultUpdatedBy
		sdtc.mutation.SetUpdatedBy(v)
	}
	if _, ok := sdtc.mutation.CreatedAt(); !ok {
		v := sysdicttype.DefaultCreatedAt()
		sdtc.mutation.SetCreatedAt(v)
	}
	if _, ok := sdtc.mutation.UpdatedAt(); !ok {
		v := sysdicttype.DefaultUpdatedAt()
		sdtc.mutation.SetUpdatedAt(v)
	}
	if _, ok := sdtc.mutation.Status(); !ok {
		v := sysdicttype.DefaultStatus
		sdtc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sdtc *SysDictTypeCreate) check() error {
	if _, ok := sdtc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "SysDictType.created_by"`)}
	}
	if _, ok := sdtc.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "SysDictType.updated_by"`)}
	}
	if _, ok := sdtc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysDictType.created_at"`)}
	}
	if _, ok := sdtc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SysDictType.updated_at"`)}
	}
	if _, ok := sdtc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SysDictType.name"`)}
	}
	if _, ok := sdtc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "SysDictType.type"`)}
	}
	if _, ok := sdtc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SysDictType.status"`)}
	}
	return nil
}

func (sdtc *SysDictTypeCreate) sqlSave(ctx context.Context) (*SysDictType, error) {
	if err := sdtc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sdtc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sdtc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	sdtc.mutation.id = &_node.ID
	sdtc.mutation.done = true
	return _node, nil
}

func (sdtc *SysDictTypeCreate) createSpec() (*SysDictType, *sqlgraph.CreateSpec) {
	var (
		_node = &SysDictType{config: sdtc.config}
		_spec = sqlgraph.NewCreateSpec(sysdicttype.Table, sqlgraph.NewFieldSpec(sysdicttype.FieldID, field.TypeInt64))
	)
	if id, ok := sdtc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sdtc.mutation.CreatedBy(); ok {
		_spec.SetField(sysdicttype.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := sdtc.mutation.UpdatedBy(); ok {
		_spec.SetField(sysdicttype.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := sdtc.mutation.CreatedAt(); ok {
		_spec.SetField(sysdicttype.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sdtc.mutation.UpdatedAt(); ok {
		_spec.SetField(sysdicttype.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sdtc.mutation.DeletedAt(); ok {
		_spec.SetField(sysdicttype.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := sdtc.mutation.Name(); ok {
		_spec.SetField(sysdicttype.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sdtc.mutation.GetType(); ok {
		_spec.SetField(sysdicttype.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := sdtc.mutation.Status(); ok {
		_spec.SetField(sysdicttype.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := sdtc.mutation.Remark(); ok {
		_spec.SetField(sysdicttype.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	return _node, _spec
}

// SysDictTypeCreateBulk is the builder for creating many SysDictType entities in bulk.
type SysDictTypeCreateBulk struct {
	config
	err      error
	builders []*SysDictTypeCreate
}

// Save creates the SysDictType entities in the database.
func (sdtcb *SysDictTypeCreateBulk) Save(ctx context.Context) ([]*SysDictType, error) {
	if sdtcb.err != nil {
		return nil, sdtcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sdtcb.builders))
	nodes := make([]*SysDictType, len(sdtcb.builders))
	mutators := make([]Mutator, len(sdtcb.builders))
	for i := range sdtcb.builders {
		func(i int, root context.Context) {
			builder := sdtcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysDictTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sdtcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sdtcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sdtcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sdtcb *SysDictTypeCreateBulk) SaveX(ctx context.Context) []*SysDictType {
	v, err := sdtcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sdtcb *SysDictTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := sdtcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sdtcb *SysDictTypeCreateBulk) ExecX(ctx context.Context) {
	if err := sdtcb.Exec(ctx); err != nil {
		panic(err)
	}
}
