// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gokeep/server/internal/ent/sysmenu"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysMenuCreate is the builder for creating a SysMenu entity.
type SysMenuCreate struct {
	config
	mutation *SysMenuMutation
	hooks    []Hook
}

// SetCreatedBy sets the "created_by" field.
func (smc *SysMenuCreate) SetCreatedBy(s string) *SysMenuCreate {
	smc.mutation.SetCreatedBy(s)
	return smc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillableCreatedBy(s *string) *SysMenuCreate {
	if s != nil {
		smc.SetCreatedBy(*s)
	}
	return smc
}

// SetUpdatedBy sets the "updated_by" field.
func (smc *SysMenuCreate) SetUpdatedBy(s string) *SysMenuCreate {
	smc.mutation.SetUpdatedBy(s)
	return smc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillableUpdatedBy(s *string) *SysMenuCreate {
	if s != nil {
		smc.SetUpdatedBy(*s)
	}
	return smc
}

// SetCreatedAt sets the "created_at" field.
func (smc *SysMenuCreate) SetCreatedAt(t time.Time) *SysMenuCreate {
	smc.mutation.SetCreatedAt(t)
	return smc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillableCreatedAt(t *time.Time) *SysMenuCreate {
	if t != nil {
		smc.SetCreatedAt(*t)
	}
	return smc
}

// SetUpdatedAt sets the "updated_at" field.
func (smc *SysMenuCreate) SetUpdatedAt(t time.Time) *SysMenuCreate {
	smc.mutation.SetUpdatedAt(t)
	return smc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillableUpdatedAt(t *time.Time) *SysMenuCreate {
	if t != nil {
		smc.SetUpdatedAt(*t)
	}
	return smc
}

// SetDeletedAt sets the "deleted_at" field.
func (smc *SysMenuCreate) SetDeletedAt(t time.Time) *SysMenuCreate {
	smc.mutation.SetDeletedAt(t)
	return smc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillableDeletedAt(t *time.Time) *SysMenuCreate {
	if t != nil {
		smc.SetDeletedAt(*t)
	}
	return smc
}

// SetParentID sets the "parent_id" field.
func (smc *SysMenuCreate) SetParentID(i int64) *SysMenuCreate {
	smc.mutation.SetParentID(i)
	return smc
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillableParentID(i *int64) *SysMenuCreate {
	if i != nil {
		smc.SetParentID(*i)
	}
	return smc
}

// SetName sets the "name" field.
func (smc *SysMenuCreate) SetName(s string) *SysMenuCreate {
	smc.mutation.SetName(s)
	return smc
}

// SetMenuType sets the "menu_type" field.
func (smc *SysMenuCreate) SetMenuType(s string) *SysMenuCreate {
	smc.mutation.SetMenuType(s)
	return smc
}

// SetNillableMenuType sets the "menu_type" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillableMenuType(s *string) *SysMenuCreate {
	if s != nil {
		smc.SetMenuType(*s)
	}
	return smc
}

// SetPath sets the "path" field.
func (smc *SysMenuCreate) SetPath(s string) *SysMenuCreate {
	smc.mutation.SetPath(s)
	return smc
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillablePath(s *string) *SysMenuCreate {
	if s != nil {
		smc.SetPath(*s)
	}
	return smc
}

// SetComponent sets the "component" field.
func (smc *SysMenuCreate) SetComponent(s string) *SysMenuCreate {
	smc.mutation.SetComponent(s)
	return smc
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillableComponent(s *string) *SysMenuCreate {
	if s != nil {
		smc.SetComponent(*s)
	}
	return smc
}

// SetPerms sets the "perms" field.
func (smc *SysMenuCreate) SetPerms(s string) *SysMenuCreate {
	smc.mutation.SetPerms(s)
	return smc
}

// SetNillablePerms sets the "perms" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillablePerms(s *string) *SysMenuCreate {
	if s != nil {
		smc.SetPerms(*s)
	}
	return smc
}

// SetIcon sets the "icon" field.
func (smc *SysMenuCreate) SetIcon(s string) *SysMenuCreate {
	smc.mutation.SetIcon(s)
	return smc
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillableIcon(s *string) *SysMenuCreate {
	if s != nil {
		smc.SetIcon(*s)
	}
	return smc
}

// SetOrderNum sets the "order_num" field.
func (smc *SysMenuCreate) SetOrderNum(i int) *SysMenuCreate {
	smc.mutation.SetOrderNum(i)
	return smc
}

// SetNillableOrderNum sets the "order_num" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillableOrderNum(i *int) *SysMenuCreate {
	if i != nil {
		smc.SetOrderNum(*i)
	}
	return smc
}

// SetVisible sets the "visible" field.
func (smc *SysMenuCreate) SetVisible(b bool) *SysMenuCreate {
	smc.mutation.SetVisible(b)
	return smc
}

// SetNillableVisible sets the "visible" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillableVisible(b *bool) *SysMenuCreate {
	if b != nil {
		smc.SetVisible(*b)
	}
	return smc
}

// SetStatus sets the "status" field.
func (smc *SysMenuCreate) SetStatus(s string) *SysMenuCreate {
	smc.mutation.SetStatus(s)
	return smc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillableStatus(s *string) *SysMenuCreate {
	if s != nil {
		smc.SetStatus(*s)
	}
	return smc
}

// SetRemark sets the "remark" field.
func (smc *SysMenuCreate) SetRemark(s string) *SysMenuCreate {
	smc.mutation.SetRemark(s)
	return smc
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (smc *SysMenuCreate) SetNillableRemark(s *string) *SysMenuCreate {
	if s != nil {
		smc.SetRemark(*s)
	}
	return smc
}

// SetID sets the "id" field.
func (smc *SysMenuCreate) SetID(i int64) *SysMenuCreate {
	smc.mutation.SetID(i)
	return smc
}

// Mutation returns the SysMenuMutation object of the builder.
func (smc *SysMenuCreate) Mutation() *SysMenuMutation {
	return smc.mutation
}

// Save creates the SysMenu in the database.
func (smc *SysMenuCreate) Save(ctx context.Context) (*SysMenu, error) {
	smc.defaults()
	return withHooks(ctx, smc.sqlSave, smc.mutation, smc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (smc *SysMenuCreate) SaveX(ctx context.Context) *SysMenu {
	v, err := smc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (smc *SysMenuCreate) Exec(ctx context.Context) error {
	_, err := smc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (smc *SysMenuCreate) ExecX(ctx context.Context) {
	if err := smc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (smc *SysMenuCreate) defaults() {
	if _, ok := smc.mutation.CreatedBy(); !ok {
		v := sysmenu.DefaultCreatedBy
		smc.mutation.SetCreatedBy(v)
	}
	if _, ok := smc.mutation.UpdatedBy(); !ok {
		v := sysmenu.DefaultUpdatedBy
		smc.mutation.SetUpdatedBy(v)
	}
	if _, ok := smc.mutation.CreatedAt(); !ok {
		v := sysmenu.DefaultCreatedAt()
		smc.mutation.SetCreatedAt(v)
	}
	if _, ok := smc.mutation.UpdatedAt(); !ok {
		v := sysmenu.DefaultUpdatedAt()
		smc.mutation.SetUpdatedAt(v)
	}
	if _, ok := smc.mutation.ParentID(); !ok {
		v := sysmenu.DefaultParentID
		smc.mutation.SetParentID(v)
	}
	if _, ok := smc.mutation.MenuType(); !ok {
		v := sysmenu.DefaultMenuType
		smc.mutation.SetMenuType(v)
	}
	if _, ok := smc.mutation.Path(); !ok {
		v := sysmenu.DefaultPath
		smc.mutation.SetPath(v)
	}
	if _, ok := smc.mutation.OrderNum(); !ok {
		v := sysmenu.DefaultOrderNum
		smc.mutation.SetOrderNum(v)
	}
	if _, ok := smc.mutation.Visible(); !ok {
		v := sysmenu.DefaultVisible
		smc.mutation.SetVisible(v)
	}
	if _, ok := smc.mutation.Status(); !ok {
		v := sysmenu.DefaultStatus
		smc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (smc *SysMenuCreate) check() error {
	if _, ok := smc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "SysMenu.created_by"`)}
	}
	if _, ok := smc.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "SysMenu.updated_by"`)}
	}
	if _, ok := smc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysMenu.created_at"`)}
	}
	if _, ok := smc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SysMenu.updated_at"`)}
	}
	if _, ok := smc.mutation.ParentID(); !ok {
		return &ValidationError{Name: "parent_id", err: errors.New(`ent: missing required field "SysMenu.parent_id"`)}
	}
	if _, ok := smc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SysMenu.name"`)}
	}
	if _, ok := smc.mutation.MenuType(); !ok {
		return &ValidationError{Name: "menu_type", err: errors.New(`ent: missing required field "SysMenu.menu_type"`)}
	}
	if _, ok := smc.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "SysMenu.path"`)}
	}
	if _, ok := smc.mutation.OrderNum(); !ok {
		return &ValidationError{Name: "order_num", err: errors.New(`ent: missing required field "SysMenu.order_num"`)}
	}
	if _, ok := smc.mutation.Visible(); !ok {
		return &ValidationError{Name: "visible", err: errors.New(`ent: missing required field "SysMenu.visible"`)}
	}
	if _, ok := smc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SysMenu.status"`)}
	}
	return nil
}

func (smc *SysMenuCreate) sqlSave(ctx context.Context) (*SysMenu, error) {
	if err := smc.check(); err != nil {
		return nil, err
	}
	_node, _spec := smc.createSpec()
	if err := sqlgraph.CreateNode(ctx, smc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	smc.mutation.id = &_node.ID
	smc.mutation.done = true
	return _node, nil
}

func (smc *SysMenuCreate) createSpec() (*SysMenu, *sqlgraph.CreateSpec) {
	var (
		_node = &SysMenu{config: smc.config}
		_spec = sqlgraph.NewCreateSpec(sysmenu.Table, sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64))
	)
	if id, ok := smc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := smc.mutation.CreatedBy(); ok {
		_spec.SetField(sysmenu.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := smc.mutation.UpdatedBy(); ok {
		_spec.SetField(sysmenu.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := smc.mutation.CreatedAt(); ok {
		_spec.SetField(sysmenu.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := smc.mutation.UpdatedAt(); ok {
		_spec.SetField(sysmenu.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := smc.mutation.DeletedAt(); ok {
		_spec.SetField(sysmenu.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := smc.mutation.ParentID(); ok {
		_spec.SetField(sysmenu.FieldParentID, field.TypeInt64, value)
		_node.ParentID = value
	}
	if value, ok := smc.mutation.Name(); ok {
		_spec.SetField(sysmenu.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := smc.mutation.MenuType(); ok {
		_spec.SetField(sysmenu.FieldMenuType, field.TypeString, value)
		_node.MenuType = value
	}
	if value, ok := smc.mutation.Path(); ok {
		_spec.SetField(sysmenu.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := smc.mutation.Component(); ok {
		_spec.SetField(sysmenu.FieldComponent, field.TypeString, value)
		_node.Component = &value
	}
	if value, ok := smc.mutation.Perms(); ok {
		_spec.SetField(sysmenu.FieldPerms, field.TypeString, value)
		_node.Perms = &value
	}
	if value, ok := smc.mutation.Icon(); ok {
		_spec.SetField(sysmenu.FieldIcon, field.TypeString, value)
		_node.Icon = &value
	}
	if value, ok := smc.mutation.OrderNum(); ok {
		_spec.SetField(sysmenu.FieldOrderNum, field.TypeInt, value)
		_node.OrderNum = value
	}
	if value, ok := smc.mutation.Visible(); ok {
		_spec.SetField(sysmenu.FieldVisible, field.TypeBool, value)
		_node.Visible = value
	}
	if value, ok := smc.mutation.Status(); ok {
		_spec.SetField(sysmenu.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := smc.mutation.Remark(); ok {
		_spec.SetField(sysmenu.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	return _node, _spec
}

// SysMenuCreateBulk is the builder for creating many SysMenu entities in bulk.
type SysMenuCreateBulk struct {
	config
	err      error
	builders []*SysMenuCreate
}

// Save creates the SysMenu entities in the database.
func (smcb *SysMenuCreateBulk) Save(ctx context.Context) ([]*SysMenu, error) {
	if smcb.err != nil {
		return nil, smcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(smcb.builders))
	nodes := make([]*SysMenu, len(smcb.builders))
	mutators := make([]Mutator, len(smcb.builders))
	for i := range smcb.builders {
		func(i int, root context.Context) {
			builder := smcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysMenuMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, smcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, smcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, smcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (smcb *SysMenuCreateBulk) SaveX(ctx context.Context) []*SysMenu {
	v, err := smcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (smcb *SysMenuCreateBulk) Exec(ctx context.Context) error {
	_, err := smcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (smcb *SysMenuCreateBulk) ExecX(ctx context.Context) {
	if err := smcb.Exec(ctx); err != nil {
		panic(err)
	}
}
