// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gokeep/server/internal/ent/predicate"
	"gokeep/server/internal/ent/sysmenu"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysMenuUpdate is the builder for updating SysMenu entities.
type SysMenuUpdate struct {
	config
	hooks    []Hook
	mutation *SysMenuMutation
}

// Where appends a list predicates to the SysMenuUpdate builder.
func (smu *SysMenuUpdate) Where(ps ...predicate.SysMenu) *SysMenuUpdate {
	smu.mutation.Where(ps...)
	return smu
}

// SetCreatedBy sets the "created_by" field.
func (smu *SysMenuUpdate) SetCreatedBy(s string) *SysMenuUpdate {
	smu.mutation.SetCreatedBy(s)
	return smu
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (smu *SysMenuUpdate) SetNillableCreatedBy(s *string) *SysMenuUpdate {
	if s != nil {
		smu.SetCreatedBy(*s)
	}
	return smu
}

// SetUpdatedBy sets the "updated_by" field.
func (smu *SysMenuUpdate) SetUpdatedBy(s string) *SysMenuUpdate {
	smu.mutation.SetUpdatedBy(s)
	return smu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (smu *SysMenuUpdate) SetNillableUpdatedBy(s *string) *SysMenuUpdate {
	if s != nil {
		smu.SetUpdatedBy(*s)
	}
	return smu
}

// SetUpdatedAt sets the "updated_at" field.
func (smu *SysMenuUpdate) SetUpdatedAt(t time.Time) *SysMenuUpdate {
	smu.mutation.SetUpdatedAt(t)
	return smu
}

// SetDeletedAt sets the "deleted_at" field.
func (smu *SysMenuUpdate) SetDeletedAt(t time.Time) *SysMenuUpdate {
	smu.mutation.SetDeletedAt(t)
	return smu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (smu *SysMenuUpdate) SetNillableDeletedAt(t *time.Time) *SysMenuUpdate {
	if t != nil {
		smu.SetDeletedAt(*t)
	}
	return smu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (smu *SysMenuUpdate) ClearDeletedAt() *SysMenuUpdate {
	smu.mutation.ClearDeletedAt()
	return smu
}

// SetParentID sets the "parent_id" field.
func (smu *SysMenuUpdate) SetParentID(i int64) *SysMenuUpdate {
	smu.mutation.ResetParentID()
	smu.mutation.SetParentID(i)
	return smu
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (smu *SysMenuUpdate) SetNillableParentID(i *int64) *SysMenuUpdate {
	if i != nil {
		smu.SetParentID(*i)
	}
	return smu
}

// AddParentID adds i to the "parent_id" field.
func (smu *SysMenuUpdate) AddParentID(i int64) *SysMenuUpdate {
	smu.mutation.AddParentID(i)
	return smu
}

// SetName sets the "name" field.
func (smu *SysMenuUpdate) SetName(s string) *SysMenuUpdate {
	smu.mutation.SetName(s)
	return smu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (smu *SysMenuUpdate) SetNillableName(s *string) *SysMenuUpdate {
	if s != nil {
		smu.SetName(*s)
	}
	return smu
}

// SetMenuType sets the "menu_type" field.
func (smu *SysMenuUpdate) SetMenuType(s string) *SysMenuUpdate {
	smu.mutation.SetMenuType(s)
	return smu
}

// SetNillableMenuType sets the "menu_type" field if the given value is not nil.
func (smu *SysMenuUpdate) SetNillableMenuType(s *string) *SysMenuUpdate {
	if s != nil {
		smu.SetMenuType(*s)
	}
	return smu
}

// SetPath sets the "path" field.
func (smu *SysMenuUpdate) SetPath(s string) *SysMenuUpdate {
	smu.mutation.SetPath(s)
	return smu
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (smu *SysMenuUpdate) SetNillablePath(s *string) *SysMenuUpdate {
	if s != nil {
		smu.SetPath(*s)
	}
	return smu
}

// SetComponent sets the "component" field.
func (smu *SysMenuUpdate) SetComponent(s string) *SysMenuUpdate {
	smu.mutation.SetComponent(s)
	return smu
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (smu *SysMenuUpdate) SetNillableComponent(s *string) *SysMenuUpdate {
	if s != nil {
		smu.SetComponent(*s)
	}
	return smu
}

// ClearComponent clears the value of the "component" field.
func (smu *SysMenuUpdate) ClearComponent() *SysMenuUpdate {
	smu.mutation.ClearComponent()
	return smu
}

// SetPerms sets the "perms" field.
func (smu *SysMenuUpdate) SetPerms(s string) *SysMenuUpdate {
	smu.mutation.SetPerms(s)
	return smu
}

// SetNillablePerms sets the "perms" field if the given value is not nil.
func (smu *SysMenuUpdate) SetNillablePerms(s *string) *SysMenuUpdate {
	if s != nil {
		smu.SetPerms(*s)
	}
	return smu
}

// ClearPerms clears the value of the "perms" field.
func (smu *SysMenuUpdate) ClearPerms() *SysMenuUpdate {
	smu.mutation.ClearPerms()
	return smu
}

// SetIcon sets the "icon" field.
func (smu *SysMenuUpdate) SetIcon(s string) *SysMenuUpdate {
	smu.mutation.SetIcon(s)
	return smu
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (smu *SysMenuUpdate) SetNillableIcon(s *string) *SysMenuUpdate {
	if s != nil {
		smu.SetIcon(*s)
	}
	return smu
}

// ClearIcon clears the value of the "icon" field.
func (smu *SysMenuUpdate) ClearIcon() *SysMenuUpdate {
	smu.mutation.ClearIcon()
	return smu
}

// SetOrderNum sets the "order_num" field.
func (smu *SysMenuUpdate) SetOrderNum(i int) *SysMenuUpdate {
	smu.mutation.ResetOrderNum()
	smu.mutation.SetOrderNum(i)
	return smu
}

// SetNillableOrderNum sets the "order_num" field if the given value is not nil.
func (smu *SysMenuUpdate) SetNillableOrderNum(i *int) *SysMenuUpdate {
	if i != nil {
		smu.SetOrderNum(*i)
	}
	return smu
}

// AddOrderNum adds i to the "order_num" field.
func (smu *SysMenuUpdate) AddOrderNum(i int) *SysMenuUpdate {
	smu.mutation.AddOrderNum(i)
	return smu
}

// SetVisible sets the "visible" field.
func (smu *SysMenuUpdate) SetVisible(b bool) *SysMenuUpdate {
	smu.mutation.SetVisible(b)
	return smu
}

// SetNillableVisible sets the "visible" field if the given value is not nil.
func (smu *SysMenuUpdate) SetNillableVisible(b *bool) *SysMenuUpdate {
	if b != nil {
		smu.SetVisible(*b)
	}
	return smu
}

// SetStatus sets the "status" field.
func (smu *SysMenuUpdate) SetStatus(s string) *SysMenuUpdate {
	smu.mutation.SetStatus(s)
	return smu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (smu *SysMenuUpdate) SetNillableStatus(s *string) *SysMenuUpdate {
	if s != nil {
		smu.SetStatus(*s)
	}
	return smu
}

// SetRemark sets the "remark" field.
func (smu *SysMenuUpdate) SetRemark(s string) *SysMenuUpdate {
	smu.mutation.SetRemark(s)
	return smu
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (smu *SysMenuUpdate) SetNillableRemark(s *string) *SysMenuUpdate {
	if s != nil {
		smu.SetRemark(*s)
	}
	return smu
}

// ClearRemark clears the value of the "remark" field.
func (smu *SysMenuUpdate) ClearRemark() *SysMenuUpdate {
	smu.mutation.ClearRemark()
	return smu
}

// Mutation returns the SysMenuMutation object of the builder.
func (smu *SysMenuUpdate) Mutation() *SysMenuMutation {
	return smu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (smu *SysMenuUpdate) Save(ctx context.Context) (int, error) {
	smu.defaults()
	return withHooks(ctx, smu.sqlSave, smu.mutation, smu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (smu *SysMenuUpdate) SaveX(ctx context.Context) int {
	affected, err := smu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (smu *SysMenuUpdate) Exec(ctx context.Context) error {
	_, err := smu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (smu *SysMenuUpdate) ExecX(ctx context.Context) {
	if err := smu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (smu *SysMenuUpdate) defaults() {
	if _, ok := smu.mutation.UpdatedAt(); !ok {
		v := sysmenu.UpdateDefaultUpdatedAt()
		smu.mutation.SetUpdatedAt(v)
	}
}

func (smu *SysMenuUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysmenu.Table, sysmenu.Columns, sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64))
	if ps := smu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := smu.mutation.CreatedBy(); ok {
		_spec.SetField(sysmenu.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := smu.mutation.UpdatedBy(); ok {
		_spec.SetField(sysmenu.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := smu.mutation.UpdatedAt(); ok {
		_spec.SetField(sysmenu.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := smu.mutation.DeletedAt(); ok {
		_spec.SetField(sysmenu.FieldDeletedAt, field.TypeTime, value)
	}
	if smu.mutation.DeletedAtCleared() {
		_spec.ClearField(sysmenu.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := smu.mutation.ParentID(); ok {
		_spec.SetField(sysmenu.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := smu.mutation.AddedParentID(); ok {
		_spec.AddField(sysmenu.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := smu.mutation.Name(); ok {
		_spec.SetField(sysmenu.FieldName, field.TypeString, value)
	}
	if value, ok := smu.mutation.MenuType(); ok {
		_spec.SetField(sysmenu.FieldMenuType, field.TypeString, value)
	}
	if value, ok := smu.mutation.Path(); ok {
		_spec.SetField(sysmenu.FieldPath, field.TypeString, value)
	}
	if value, ok := smu.mutation.Component(); ok {
		_spec.SetField(sysmenu.FieldComponent, field.TypeString, value)
	}
	if smu.mutation.ComponentCleared() {
		_spec.ClearField(sysmenu.FieldComponent, field.TypeString)
	}
	if value, ok := smu.mutation.Perms(); ok {
		_spec.SetField(sysmenu.FieldPerms, field.TypeString, value)
	}
	if smu.mutation.PermsCleared() {
		_spec.ClearField(sysmenu.FieldPerms, field.TypeString)
	}
	if value, ok := smu.mutation.Icon(); ok {
		_spec.SetField(sysmenu.FieldIcon, field.TypeString, value)
	}
	if smu.mutation.IconCleared() {
		_spec.ClearField(sysmenu.FieldIcon, field.TypeString)
	}
	if value, ok := smu.mutation.OrderNum(); ok {
		_spec.SetField(sysmenu.FieldOrderNum, field.TypeInt, value)
	}
	if value, ok := smu.mutation.AddedOrderNum(); ok {
		_spec.AddField(sysmenu.FieldOrderNum, field.TypeInt, value)
	}
	if value, ok := smu.mutation.Visible(); ok {
		_spec.SetField(sysmenu.FieldVisible, field.TypeBool, value)
	}
	if value, ok := smu.mutation.Status(); ok {
		_spec.SetField(sysmenu.FieldStatus, field.TypeString, value)
	}
	if value, ok := smu.mutation.Remark(); ok {
		_spec.SetField(sysmenu.FieldRemark, field.TypeString, value)
	}
	if smu.mutation.RemarkCleared() {
		_spec.ClearField(sysmenu.FieldRemark, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, smu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysmenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	smu.mutation.done = true
	return n, nil
}

// SysMenuUpdateOne is the builder for updating a single SysMenu entity.
type SysMenuUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysMenuMutation
}

// SetCreatedBy sets the "created_by" field.
func (smuo *SysMenuUpdateOne) SetCreatedBy(s string) *SysMenuUpdateOne {
	smuo.mutation.SetCreatedBy(s)
	return smuo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (smuo *SysMenuUpdateOne) SetNillableCreatedBy(s *string) *SysMenuUpdateOne {
	if s != nil {
		smuo.SetCreatedBy(*s)
	}
	return smuo
}

// SetUpdatedBy sets the "updated_by" field.
func (smuo *SysMenuUpdateOne) SetUpdatedBy(s string) *SysMenuUpdateOne {
	smuo.mutation.SetUpdatedBy(s)
	return smuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (smuo *SysMenuUpdateOne) SetNillableUpdatedBy(s *string) *SysMenuUpdateOne {
	if s != nil {
		smuo.SetUpdatedBy(*s)
	}
	return smuo
}

// SetUpdatedAt sets the "updated_at" field.
func (smuo *SysMenuUpdateOne) SetUpdatedAt(t time.Time) *SysMenuUpdateOne {
	smuo.mutation.SetUpdatedAt(t)
	return smuo
}

// SetDeletedAt sets the "deleted_at" field.
func (smuo *SysMenuUpdateOne) SetDeletedAt(t time.Time) *SysMenuUpdateOne {
	smuo.mutation.SetDeletedAt(t)
	return smuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (smuo *SysMenuUpdateOne) SetNillableDeletedAt(t *time.Time) *SysMenuUpdateOne {
	if t != nil {
		smuo.SetDeletedAt(*t)
	}
	return smuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (smuo *SysMenuUpdateOne) ClearDeletedAt() *SysMenuUpdateOne {
	smuo.mutation.ClearDeletedAt()
	return smuo
}

// SetParentID sets the "parent_id" field.
func (smuo *SysMenuUpdateOne) SetParentID(i int64) *SysMenuUpdateOne {
	smuo.mutation.ResetParentID()
	smuo.mutation.SetParentID(i)
	return smuo
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (smuo *SysMenuUpdateOne) SetNillableParentID(i *int64) *SysMenuUpdateOne {
	if i != nil {
		smuo.SetParentID(*i)
	}
	return smuo
}

// AddParentID adds i to the "parent_id" field.
func (smuo *SysMenuUpdateOne) AddParentID(i int64) *SysMenuUpdateOne {
	smuo.mutation.AddParentID(i)
	return smuo
}

// SetName sets the "name" field.
func (smuo *SysMenuUpdateOne) SetName(s string) *SysMenuUpdateOne {
	smuo.mutation.SetName(s)
	return smuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (smuo *SysMenuUpdateOne) SetNillableName(s *string) *SysMenuUpdateOne {
	if s != nil {
		smuo.SetName(*s)
	}
	return smuo
}

// SetMenuType sets the "menu_type" field.
func (smuo *SysMenuUpdateOne) SetMenuType(s string) *SysMenuUpdateOne {
	smuo.mutation.SetMenuType(s)
	return smuo
}

// SetNillableMenuType sets the "menu_type" field if the given value is not nil.
func (smuo *SysMenuUpdateOne) SetNillableMenuType(s *string) *SysMenuUpdateOne {
	if s != nil {
		smuo.SetMenuType(*s)
	}
	return smuo
}

// SetPath sets the "path" field.
func (smuo *SysMenuUpdateOne) SetPath(s string) *SysMenuUpdateOne {
	smuo.mutation.SetPath(s)
	return smuo
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (smuo *SysMenuUpdateOne) SetNillablePath(s *string) *SysMenuUpdateOne {
	if s != nil {
		smuo.SetPath(*s)
	}
	return smuo
}

// SetComponent sets the "component" field.
func (smuo *SysMenuUpdateOne) SetComponent(s string) *SysMenuUpdateOne {
	smuo.mutation.SetComponent(s)
	return smuo
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (smuo *SysMenuUpdateOne) SetNillableComponent(s *string) *SysMenuUpdateOne {
	if s != nil {
		smuo.SetComponent(*s)
	}
	return smuo
}

// ClearComponent clears the value of the "component" field.
func (smuo *SysMenuUpdateOne) ClearComponent() *SysMenuUpdateOne {
	smuo.mutation.ClearComponent()
	return smuo
}

// SetPerms sets the "perms" field.
func (smuo *SysMenuUpdateOne) SetPerms(s string) *SysMenuUpdateOne {
	smuo.mutation.SetPerms(s)
	return smuo
}

// SetNillablePerms sets the "perms" field if the given value is not nil.
func (smuo *SysMenuUpdateOne) SetNillablePerms(s *string) *SysMenuUpdateOne {
	if s != nil {
		smuo.SetPerms(*s)
	}
	return smuo
}

// ClearPerms clears the value of the "perms" field.
func (smuo *SysMenuUpdateOne) ClearPerms() *SysMenuUpdateOne {
	smuo.mutation.ClearPerms()
	return smuo
}

// SetIcon sets the "icon" field.
func (smuo *SysMenuUpdateOne) SetIcon(s string) *SysMenuUpdateOne {
	smuo.mutation.SetIcon(s)
	return smuo
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (smuo *SysMenuUpdateOne) SetNillableIcon(s *string) *SysMenuUpdateOne {
	if s != nil {
		smuo.SetIcon(*s)
	}
	return smuo
}

// ClearIcon clears the value of the "icon" field.
func (smuo *SysMenuUpdateOne) ClearIcon() *SysMenuUpdateOne {
	smuo.mutation.ClearIcon()
	return smuo
}

// SetOrderNum sets the "order_num" field.
func (smuo *SysMenuUpdateOne) SetOrderNum(i int) *SysMenuUpdateOne {
	smuo.mutation.ResetOrderNum()
	smuo.mutation.SetOrderNum(i)
	return smuo
}

// SetNillableOrderNum sets the "order_num" field if the given value is not nil.
func (smuo *SysMenuUpdateOne) SetNillableOrderNum(i *int) *SysMenuUpdateOne {
	if i != nil {
		smuo.SetOrderNum(*i)
	}
	return smuo
}

// AddOrderNum adds i to the "order_num" field.
func (smuo *SysMenuUpdateOne) AddOrderNum(i int) *SysMenuUpdateOne {
	smuo.mutation.AddOrderNum(i)
	return smuo
}

// SetVisible sets the "visible" field.
func (smuo *SysMenuUpdateOne) SetVisible(b bool) *SysMenuUpdateOne {
	smuo.mutation.SetVisible(b)
	return smuo
}

// SetNillableVisible sets the "visible" field if the given value is not nil.
func (smuo *SysMenuUpdateOne) SetNillableVisible(b *bool) *SysMenuUpdateOne {
	if b != nil {
		smuo.SetVisible(*b)
	}
	return smuo
}

// SetStatus sets the "status" field.
func (smuo *SysMenuUpdateOne) SetStatus(s string) *SysMenuUpdateOne {
	smuo.mutation.SetStatus(s)
	return smuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (smuo *SysMenuUpdateOne) SetNillableStatus(s *string) *SysMenuUpdateOne {
	if s != nil {
		smuo.SetStatus(*s)
	}
	return smuo
}

// SetRemark sets the "remark" field.
func (smuo *SysMenuUpdateOne) SetRemark(s string) *SysMenuUpdateOne {
	smuo.mutation.SetRemark(s)
	return smuo
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (smuo *SysMenuUpdateOne) SetNillableRemark(s *string) *SysMenuUpdateOne {
	if s != nil {
		smuo.SetRemark(*s)
	}
	return smuo
}

// ClearRemark clears the value of the "remark" field.
func (smuo *SysMenuUpdateOne) ClearRemark() *SysMenuUpdateOne {
	smuo.mutation.ClearRemark()
	return smuo
}

// Mutation returns the SysMenuMutation object of the builder.
func (smuo *SysMenuUpdateOne) Mutation() *SysMenuMutation {
	return smuo.mutation
}

// Where appends a list predicates to the SysMenuUpdate builder.
func (smuo *SysMenuUpdateOne) Where(ps ...predicate.SysMenu) *SysMenuUpdateOne {
	smuo.mutation.Where(ps...)
	return smuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (smuo *SysMenuUpdateOne) Select(field string, fields ...string) *SysMenuUpdateOne {
	smuo.fields = append([]string{field}, fields...)
	return smuo
}

// Save executes the query and returns the updated SysMenu entity.
func (smuo *SysMenuUpdateOne) Save(ctx context.Context) (*SysMenu, error) {
	smuo.defaults()
	return withHooks(ctx, smuo.sqlSave, smuo.mutation, smuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (smuo *SysMenuUpdateOne) SaveX(ctx context.Context) *SysMenu {
	node, err := smuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (smuo *SysMenuUpdateOne) Exec(ctx context.Context) error {
	_, err := smuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (smuo *SysMenuUpdateOne) ExecX(ctx context.Context) {
	if err := smuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (smuo *SysMenuUpdateOne) defaults() {
	if _, ok := smuo.mutation.UpdatedAt(); !ok {
		v := sysmenu.UpdateDefaultUpdatedAt()
		smuo.mutation.SetUpdatedAt(v)
	}
}

func (smuo *SysMenuUpdateOne) sqlSave(ctx context.Context) (_node *SysMenu, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysmenu.Table, sysmenu.Columns, sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64))
	id, ok := smuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysMenu.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := smuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysmenu.FieldID)
		for _, f := range fields {
			if !sysmenu.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysmenu.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := smuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := smuo.mutation.CreatedBy(); ok {
		_spec.SetField(sysmenu.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := smuo.mutation.UpdatedBy(); ok {
		_spec.SetField(sysmenu.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := smuo.mutation.UpdatedAt(); ok {
		_spec.SetField(sysmenu.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := smuo.mutation.DeletedAt(); ok {
		_spec.SetField(sysmenu.FieldDeletedAt, field.TypeTime, value)
	}
	if smuo.mutation.DeletedAtCleared() {
		_spec.ClearField(sysmenu.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := smuo.mutation.ParentID(); ok {
		_spec.SetField(sysmenu.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := smuo.mutation.AddedParentID(); ok {
		_spec.AddField(sysmenu.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := smuo.mutation.Name(); ok {
		_spec.SetField(sysmenu.FieldName, field.TypeString, value)
	}
	if value, ok := smuo.mutation.MenuType(); ok {
		_spec.SetField(sysmenu.FieldMenuType, field.TypeString, value)
	}
	if value, ok := smuo.mutation.Path(); ok {
		_spec.SetField(sysmenu.FieldPath, field.TypeString, value)
	}
	if value, ok := smuo.mutation.Component(); ok {
		_spec.SetField(sysmenu.FieldComponent, field.TypeString, value)
	}
	if smuo.mutation.ComponentCleared() {
		_spec.ClearField(sysmenu.FieldComponent, field.TypeString)
	}
	if value, ok := smuo.mutation.Perms(); ok {
		_spec.SetField(sysmenu.FieldPerms, field.TypeString, value)
	}
	if smuo.mutation.PermsCleared() {
		_spec.ClearField(sysmenu.FieldPerms, field.TypeString)
	}
	if value, ok := smuo.mutation.Icon(); ok {
		_spec.SetField(sysmenu.FieldIcon, field.TypeString, value)
	}
	if smuo.mutation.IconCleared() {
		_spec.ClearField(sysmenu.FieldIcon, field.TypeString)
	}
	if value, ok := smuo.mutation.OrderNum(); ok {
		_spec.SetField(sysmenu.FieldOrderNum, field.TypeInt, value)
	}
	if value, ok := smuo.mutation.AddedOrderNum(); ok {
		_spec.AddField(sysmenu.FieldOrderNum, field.TypeInt, value)
	}
	if value, ok := smuo.mutation.Visible(); ok {
		_spec.SetField(sysmenu.FieldVisible, field.TypeBool, value)
	}
	if value, ok := smuo.mutation.Status(); ok {
		_spec.SetField(sysmenu.FieldStatus, field.TypeString, value)
	}
	if value, ok := smuo.mutation.Remark(); ok {
		_spec.SetField(sysmenu.FieldRemark, field.TypeString, value)
	}
	if smuo.mutation.RemarkCleared() {
		_spec.ClearField(sysmenu.FieldRemark, field.TypeString)
	}
	_node = &SysMenu{config: smuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, smuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysmenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	smuo.mutation.done = true
	return _node, nil
}
