// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gokeep/server/internal/ent/sysoperlog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysOperLogCreate is the builder for creating a SysOperLog entity.
type SysOperLogCreate struct {
	config
	mutation *SysOperLogMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (solc *SysOperLogCreate) SetTitle(s string) *SysOperLogCreate {
	solc.mutation.SetTitle(s)
	return solc
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (solc *SysOperLogCreate) SetNillableTitle(s *string) *SysOperLogCreate {
	if s != nil {
		solc.SetTitle(*s)
	}
	return solc
}

// SetBusinessType sets the "business_type" field.
func (solc *SysOperLogCreate) SetBusinessType(s string) *SysOperLogCreate {
	solc.mutation.SetBusinessType(s)
	return solc
}

// SetNillableBusinessType sets the "business_type" field if the given value is not nil.
func (solc *SysOperLogCreate) SetNillableBusinessType(s *string) *SysOperLogCreate {
	if s != nil {
		solc.SetBusinessType(*s)
	}
	return solc
}

// SetMethod sets the "method" field.
func (solc *SysOperLogCreate) SetMethod(s string) *SysOperLogCreate {
	solc.mutation.SetMethod(s)
	return solc
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (solc *SysOperLogCreate) SetNillableMethod(s *string) *SysOperLogCreate {
	if s != nil {
		solc.SetMethod(*s)
	}
	return solc
}

// SetPath sets the "path" field.
func (solc *SysOperLogCreate) SetPath(s string) *SysOperLogCreate {
	solc.mutation.SetPath(s)
	return solc
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (solc *SysOperLogCreate) SetNillablePath(s *string) *SysOperLogCreate {
	if s != nil {
		solc.SetPath(*s)
	}
	return solc
}

// SetOperatorID sets the "operator_id" field.
func (solc *SysOperLogCreate) SetOperatorID(i int64) *SysOperLogCreate {
	solc.mutation.SetOperatorID(i)
	return solc
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (solc *SysOperLogCreate) SetNillableOperatorID(i *int64) *SysOperLogCreate {
	if i != nil {
		solc.SetOperatorID(*i)
	}
	return solc
}

// SetOperatorName sets the "operator_name" field.
func (solc *SysOperLogCreate) SetOperatorName(s string) *SysOperLogCreate {
	solc.mutation.SetOperatorName(s)
	return solc
}

// SetNillableOperatorName sets the "operator_name" field if the given value is not nil.
func (solc *SysOperLogCreate) SetNillableOperatorName(s *string) *SysOperLogCreate {
	if s != nil {
		solc.SetOperatorName(*s)
	}
	return solc
}

// SetIP sets the "ip" field.
func (solc *SysOperLogCreate) SetIP(s string) *SysOperLogCreate {
	solc.mutation.SetIP(s)
	return solc
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (solc *SysOperLogCreate) SetNillableIP(s *string) *SysOperLogCreate {
	if s != nil {
		solc.SetIP(*s)
	}
	return solc
}

// SetStatusCode sets the "status_code" field.
func (solc *SysOperLogCreate) SetStatusCode(i int) *SysOperLogCreate {
	solc.mutation.SetStatusCode(i)
	return solc
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (solc *SysOperLogCreate) SetNillableStatusCode(i *int) *SysOperLogCreate {
	if i != nil {
		solc.SetStatusCode(*i)
	}
	return solc
}

// SetDurationMs sets the "duration_ms" field.
func (solc *SysOperLogCreate) SetDurationMs(i int64) *SysOperLogCreate {
	solc.mutation.SetDurationMs(i)
	return solc
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (solc *SysOperLogCreate) SetNillableDurationMs(i *int64) *SysOperLogCreate {
	if i != nil {
		solc.SetDurationMs(*i)
	}
	return solc
}

// SetParams sets the "params" field.
func (solc *SysOperLogCreate) SetParams(s string) *SysOperLogCreate {
	solc.mutation.SetParams(s)
	return solc
}

// SetNillableParams sets the "params" field if the given value is not nil.
func (solc *SysOperLogCreate) SetNillableParams(s *string) *SysOperLogCreate {
	if s != nil {
		solc.SetParams(*s)
	}
	return solc
}

// SetError sets the "error" field.
func (solc *SysOperLogCreate) SetError(s string) *SysOperLogCreate {
	solc.mutation.SetError(s)
	return solc
}

// SetNillableError sets the "error" field if the given value is not nil.
func (solc *SysOperLogCreate) SetNillableError(s *string) *SysOperLogCreate {
	if s != nil {
		solc.SetError(*s)
	}
	return solc
}

// SetCreatedAt sets the "created_at" field.
func (solc *SysOperLogCreate) SetCreatedAt(t time.Time) *SysOperLogCreate {
	solc.mutation.SetCreatedAt(t)
	return solc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (solc *SysOperLogCreate) SetNillableCreatedAt(t *time.Time) *SysOperLogCreate {
	if t != nil {
		solc.SetCreatedAt(*t)
	}
	return solc
}

// SetID sets the "id" field.
func (solc *SysOperLogCreate) SetID(i int64) *SysOperLogCreate {
	solc.mutation.SetID(i)
	return solc
}

// Mutation returns the SysOperLogMutation object of the builder.
func (solc *SysOperLogCreate) Mutation() *SysOperLogMutation {
	return solc.mutation
}

// Save creates the SysOperLog in the database.
func (solc *SysOperLogCreate) Save(ctx context.Context) (*SysOperLog, error) {
	solc.defaults()
	return withHooks(ctx, solc.sqlSave, solc.mutation, solc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (solc *SysOperLogCreate) SaveX(ctx context.Context) *SysOperLog {
	v, err := solc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (solc *SysOperLogCreate) Exec(ctx context.Context) error {
	_, err := solc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (solc *SysOperLogCreate) ExecX(ctx context.Context) {
	if err := solc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (solc *SysOperLogCreate) defaults() {
	if _, ok := solc.mutation.Title(); !ok {
		v := sysoperlog.DefaultTitle
		solc.mutation.SetTitle(v)
	}
	if _, ok := solc.mutation.BusinessType(); !ok {
		v := sysoperlog.DefaultBusinessType
		solc.mutation.SetBusinessType(v)
	}
	if _, ok := solc.mutation.Method(); !ok {
		v := sysoperlog.DefaultMethod
		solc.mutation.SetMethod(v)
	}
	if _, ok := solc.mutation.Path(); !ok {
		v := sysoperlog.DefaultPath
		solc.mutation.SetPath(v)
	}
	if _, ok := solc.mutation.OperatorName(); !ok {
		v := sysoperlog.DefaultOperatorName
		solc.mutation.SetOperatorName(v)
	}
	if _, ok := solc.mutation.IP(); !ok {
		v := sysoperlog.DefaultIP
		solc.mutation.SetIP(v)
	}
	if _, ok := solc.mutation.StatusCode(); !ok {
		v := sysoperlog.DefaultStatusCode
		solc.mutation.SetStatusCode(v)
	}
	if _, ok := solc.mutation.DurationMs(); !ok {
		v := sysoperlog.DefaultDurationMs
		solc.mutation.SetDurationMs(v)
	}
	if _, ok := solc.mutation.CreatedAt(); !ok {
		v := sysoperlog.DefaultCreatedAt()
		solc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (solc *SysOperLogCreate) check() error {
	if _, ok := solc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "SysOperLog.title"`)}
	}
	if _, ok := solc.mutation.BusinessType(); !ok {
		return &ValidationError{Name: "business_type", err: errors.New(`ent: missing required field "SysOperLog.business_type"`)}
	}
	if _, ok := solc.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "SysOperLog.method"`)}
	}
	if _, ok := solc.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "SysOperLog.path"`)}
	}
	if _, ok := solc.mutation.OperatorName(); !ok {
		return &ValidationError{Name: "operator_name", err: errors.New(`ent: missing required field "SysOperLog.operator_name"`)}
	}
	if _, ok := solc.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "SysOperLog.ip"`)}
	}
	if _, ok := solc.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "SysOperLog.status_code"`)}
	}
	if _, ok := solc.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "SysOperLog.duration_ms"`)}
	}
	if _, ok := solc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysOperLog.created_at"`)}
	}
	return nil
}

func (solc *SysOperLogCreate) sqlSave(ctx context.Context) (*SysOperLog, error) {
	if err := solc.check(); err != nil {
		return nil, err
	}
	_node, _spec := solc.createSpec()
	if err := sqlgraph.CreateNode(ctx, solc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	solc.mutation.id = &_node.ID
	solc.mutation.done = true
	return _node, nil
}

func (solc *SysOperLogCreate) createSpec() (*SysOperLog, *sqlgraph.CreateSpec) {
	var (
		_node = &SysOperLog{config: solc.config}
		_spec = sqlgraph.NewCreateSpec(sysoperlog.Table, sqlgraph.NewFieldSpec(sysoperlog.FieldID, field.TypeInt64))
	)
	if id, ok := solc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := solc.mutation.Title(); ok {
		_spec.SetField(sysoperlog.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := solc.mutation.BusinessType(); ok {
		_spec.SetField(sysoperlog.FieldBusinessType, field.TypeString, value)
		_node.BusinessType = value
	}
	if value, ok := solc.mutation.Method(); ok {
		_spec.SetField(sysoperlog.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := solc.mutation.Path(); ok {
		_spec.SetField(sysoperlog.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := solc.mutation.OperatorID(); ok {
		_spec.SetField(sysoperlog.FieldOperatorID, field.TypeInt64, value)
		_node.OperatorID = &value
	}
	if value, ok := solc.mutation.OperatorName(); ok {
		_spec.SetField(sysoperlog.FieldOperatorName, field.TypeString, value)
		_node.OperatorName = value
	}
	if value, ok := solc.mutation.IP(); ok {
		_spec.SetField(sysoperlog.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := solc.mutation.StatusCode(); ok {
		_spec.SetField(sysoperlog.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := solc.mutation.DurationMs(); ok {
		_spec.SetField(sysoperlog.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := solc.mutation.Params(); ok {
		_spec.SetField(sysoperlog.FieldParams, field.TypeString, value)
		_node.Params = &value
	}
	if value, ok := solc.mutation.Error(); ok {
		_spec.SetField(sysoperlog.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	if value, ok := solc.mutation.CreatedAt(); ok {
		_spec.SetField(sysoperlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// SysOperLogCreateBulk is the builder for creating many SysOperLog entities in bulk.
type SysOperLogCreateBulk struct {
	config
	err      error
	builders []*SysOperLogCreate
}

// Save creates the SysOperLog entities in the database.
func (solcb *SysOperLogCreateBulk) Save(ctx context.Context) ([]*SysOperLog, error) {
	if solcb.err != nil {
		return nil, solcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(solcb.builders))
	nodes := make([]*SysOperLog, len(solcb.builders))
	mutators := make([]Mutator, len(solcb.builders))
	for i := range solcb.builders {
		func(i int, root context.Context) {
			builder := solcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysOperLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, solcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, solcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, solcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (solcb *SysOperLogCreateBulk) SaveX(ctx context.Context) []*SysOperLog {
	v, err := solcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (solcb *SysOperLogCreateBulk) Exec(ctx context.Context) error {
	_, err := solcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (solcb *SysOperLogCreateBulk) ExecX(ctx context.Context) {
	if err := solcb.Exec(ctx); err != nil {
		panic(err)
	}
}
