// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gokeep/server/internal/ent/sysoperlog"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SysOperLog is the model entity for the SysOperLog schema.
type SysOperLog struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID int64 `json:"id,omitempty"`
	// 模块标题
	Title string `json:"title,omitempty"`
	// 业务类型（OTHER/INSERT/UPDATE/DELETE/GRANT/EXPORT）
	BusinessType string `json:"business_type,omitempty"`
	// 请求方法
	Method string `json:"method,omitempty"`
	// 请求路径
	Path string `json:"path,omitempty"`
	// 操作人ID
	OperatorID *int64 `json:"operator_id,omitempty"`
	// 操作人
	OperatorName string `json:"operator_name,omitempty"`
	// 操作IP
	IP string `json:"ip,omitempty"`
	// 响应状态码
	StatusCode int `json:"status_code,omitempty"`
	// 耗时(毫秒)
	DurationMs int64 `json:"duration_ms,omitempty"`
	// 请求参数摘要（敏感字段脱敏）
	Params *string `json:"params,omitempty"`
	// 错误信息
	Error *string `json:"error,omitempty"`
	// 操作时间
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysOperLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysoperlog.FieldID, sysoperlog.FieldOperatorID, sysoperlog.FieldStatusCode, sysoperlog.FieldDurationMs:
			values[i] = new(sql.NullInt64)
		case sysoperlog.FieldTitle, sysoperlog.FieldBusinessType, sysoperlog.FieldMethod, sysoperlog.FieldPath, sysoperlog.FieldOperatorName, sysoperlog.FieldIP, sysoperlog.FieldParams, sysoperlog.FieldError:
			values[i] = new(sql.NullString)
		case sysoperlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysOperLog fields.
func (sol *SysOperLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysoperlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sol.ID = int64(value.Int64)
		case sysoperlog.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				sol.Title = value.String
			}
		case sysoperlog.FieldBusinessType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field business_type", values[i])
			} else if value.Valid {
				sol.BusinessType = value.String
			}
		case sysoperlog.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				sol.Method = value.String
			}
		case sysoperlog.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				sol.Path = value.String
			}
		case sysoperlog.FieldOperatorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_id", values[i])
			} else if value.Valid {
				sol.OperatorID = new(int64)
				*sol.OperatorID = value.Int64
			}
		case sysoperlog.FieldOperatorName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operator_name", values[i])
			} else if value.Valid {
				sol.OperatorName = value.String
			}
		case sysoperlog.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				sol.IP = value.String
			}
		case sysoperlog.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				sol.StatusCode = int(value.Int64)
			}
		case sysoperlog.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				sol.DurationMs = value.Int64
			}
		case sysoperlog.FieldParams:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field params", values[i])
			} else if value.Valid {
				sol.Params = new(string)
				*sol.Params = value.String
			}
		case sysoperlog.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				sol.Error = new(string)
				*sol.Error = value.String
			}
		case sysoperlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sol.CreatedAt = value.Time
			}
		default:
			sol.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysOperLog.
// This includes values selected through modifiers, order, etc.
func (sol *SysOperLog) Value(name string) (ent.Value, error) {
	return sol.selectValues.Get(name)
}

// Update returns a builder for updating this SysOperLog.
// Note that you need to call SysOperLog.Unwrap() before calling this method if this SysOperLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (sol *SysOperLog) Update() *SysOperLogUpdateOne {
	return NewSysOperLogClient(sol.config).UpdateOne(sol)
}

// Unwrap unwraps the SysOperLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sol *SysOperLog) Unwrap() *SysOperLog {
	_tx, ok := sol.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysOperLog is not a transactional entity")
	}
	sol.config.driver = _tx.drv
	return sol
}

// String implements the fmt.Stringer.
func (sol *SysOperLog) String() string {
	var builder strings.Builder
	builder.WriteString("SysOperLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sol.ID))
	builder.WriteString("title=")
	builder.WriteString(sol.Title)
	builder.WriteString(", ")
	builder.WriteString("business_type=")
	builder.WriteString(sol.BusinessType)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(sol.Method)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(sol.Path)
	builder.WriteString(", ")
	if v := sol.OperatorID; v != nil {
		builder.WriteString("operator_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("operator_name=")
	builder.WriteString(sol.OperatorName)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(sol.IP)
	builder.WriteString(", ")
	builder.WriteString("status_code=")
	builder.WriteString(fmt.Sprintf("%v", sol.StatusCode))
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", sol.DurationMs))
	builder.WriteString(", ")
	if v := sol.Params; v != nil {
		builder.WriteString("params=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := sol.Error; v != nil {
		builder.WriteString("error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(sol.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SysOperLogs is a parsable slice of SysOperLog.
type SysOperLogs []*SysOperLog
