// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gokeep/server/internal/ent/predicate"
	"gokeep/server/internal/ent/sysrole"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysRoleUpdate is the builder for updating SysRole entities.
type SysRoleUpdate struct {
	config
	hooks    []Hook
	mutation *SysRoleMutation
}

// Where appends a list predicates to the SysRoleUpdate builder.
func (sru *SysRoleUpdate) Where(ps ...predicate.SysRole) *SysRoleUpdate {
	sru.mutation.Where(ps...)
	return sru
}

// SetCreatedBy sets the "created_by" field.
func (sru *SysRoleUpdate) SetCreatedBy(s string) *SysRoleUpdate {
	sru.mutation.SetCreatedBy(s)
	return sru
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (sru *SysRoleUpdate) SetNillableCreatedBy(s *string) *SysRoleUpdate {
	if s != nil {
		sru.SetCreatedBy(*s)
	}
	return sru
}

// SetUpdatedBy sets the "updated_by" field.
func (sru *SysRoleUpdate) SetUpdatedBy(s string) *SysRoleUpdate {
	sru.mutation.SetUpdatedBy(s)
	return sru
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (sru *SysRoleUpdate) SetNillableUpdatedBy(s *string) *SysRoleUpdate {
	if s != nil {
		sru.SetUpdatedBy(*s)
	}
	return sru
}

// SetUpdatedAt sets the "updated_at" field.
func (sru *SysRoleUpdate) SetUpdatedAt(t time.Time) *SysRoleUpdate {
	sru.mutation.SetUpdatedAt(t)
	return sru
}

// SetDeletedAt sets the "deleted_at" field.
func (sru *SysRoleUpdate) SetDeletedAt(t time.Time) *SysRoleUpdate {
	sru.mutation.SetDeletedAt(t)
	return sru
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sru *SysRoleUpdate) SetNillableDeletedAt(t *time.Time) *SysRoleUpdate {
	if t != nil {
		sru.SetDeletedAt(*t)
	}
	return sru
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (sru *SysRoleUpdate) ClearDeletedAt() *SysRoleUpdate {
	sru.mutation.ClearDeletedAt()
	return sru
}

// SetName sets the "name" field.
func (sru *SysRoleUpdate) SetName(s string) *SysRoleUpdate {
	sru.mutation.SetName(s)
	return sru
}

// SetNillableName sets the "name" field if the given value is not nil.
func (sru *SysRoleUpdate) SetNillableName(s *string) *SysRoleUpdate {
	if s != nil {
		sru.SetName(*s)
	}
	return sru
}

// SetCode sets the "code" field.
func (sru *SysRoleUpdate) SetCode(s string) *SysRoleUpdate {
	sru.mutation.SetCode(s)
	return sru
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (sru *SysRoleUpdate) SetNillableCode(s *string) *SysRoleUpdate {
	if s != nil {
		sru.SetCode(*s)
	}
	return sru
}

// SetSort sets the "sort" field.
func (sru *SysRoleUpdate) SetSort(i int) *SysRoleUpdate {
	sru.mutation.ResetSort()
	sru.mutation.SetSort(i)
	return sru
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (sru *SysRoleUpdate) SetNillableSort(i *int) *SysRoleUpdate {
	if i != nil {
		sru.SetSort(*i)
	}
	return sru
}

// AddSort adds i to the "sort" field.
func (sru *SysRoleUpdate) AddSort(i int) *SysRoleUpdate {
	sru.mutation.AddSort(i)
	return sru
}

// SetIsAdmin sets the "is_admin" field.
func (sru *SysRoleUpdate) SetIsAdmin(b bool) *SysRoleUpdate {
	sru.mutation.SetIsAdmin(b)
	return sru
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (sru *SysRoleUpdate) SetNillableIsAdmin(b *bool) *SysRoleUpdate {
	if b != nil {
		sru.SetIsAdmin(*b)
	}
	return sru
}

// SetStatus sets the "status" field.
func (sru *SysRoleUpdate) SetStatus(s string) *SysRoleUpdate {
	sru.mutation.SetStatus(s)
	return sru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sru *SysRoleUpdate) SetNillableStatus(s *string) *SysRoleUpdate {
	if s != nil {
		sru.SetStatus(*s)
	}
	return sru
}

// SetRemark sets the "remark" field.
func (sru *SysRoleUpdate) SetRemark(s string) *SysRoleUpdate {
	sru.mutation.SetRemark(s)
	return sru
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (sru *SysRoleUpdate) SetNillableRemark(s *string) *SysRoleUpdate {
	if s != nil {
		sru.SetRemark(*s)
	}
	return sru
}

// ClearRemark clears the value of the "remark" field.
func (sru *SysRoleUpdate) ClearRemark() *SysRoleUpdate {
	sru.mutation.ClearRemark()
	return sru
}

// Mutation returns the SysRoleMutation object of the builder.
func (sru *SysRoleUpdate) Mutation() *SysRoleMutation {
	return sru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sru *SysRoleUpdate) Save(ctx context.Context) (int, error) {
	sru.defaults()
	return withHooks(ctx, sru.sqlSave, sru.mutation, sru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sru *SysRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := sru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sru *SysRoleUpdate) Exec(ctx context.Context) error {
	_, err := sru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sru *SysRoleUpdate) ExecX(ctx context.Context) {
	if err := sru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sru *SysRoleUpdate) defaults() {
	if _, ok := sru.mutation.UpdatedAt(); !ok {
		v := sysrole.UpdateDefaultUpdatedAt()
		sru.mutation.SetUpdatedAt(v)
	}
}

func (sru *SysRoleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysrole.Table, sysrole.Columns, sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64))
	if ps := sru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sru.mutation.CreatedBy(); ok {
		_spec.SetField(sysrole.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := sru.mutation.UpdatedBy(); ok {
		_spec.SetField(sysrole.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := sru.mutation.UpdatedAt(); ok {
		_spec.SetField(sysrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := sru.mutation.DeletedAt(); ok {
		_spec.SetField(sysrole.FieldDeletedAt, field.TypeTime, value)
	}
	if sru.mutation.DeletedAtCleared() {
		_spec.ClearField(sysrole.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := sru.mutation.Name(); ok {
		_spec.SetField(sysrole.FieldName, field.TypeString, value)
	}
	if value, ok := sru.mutation.Code(); ok {
		_spec.SetField(sysrole.FieldCode, field.TypeString, value)
	}
	if value, ok := sru.mutation.Sort(); ok {
		_spec.SetField(sysrole.FieldSort, field.TypeInt, value)
	}
	if value, ok := sru.mutation.AddedSort(); ok {
		_spec.AddField(sysrole.FieldSort, field.TypeInt, value)
	}
	if value, ok := sru.mutation.IsAdmin(); ok {
		_spec.SetField(sysrole.FieldIsAdmin, field.TypeBool, value)
	}
	if value, ok := sru.mutation.Status(); ok {
		_spec.SetField(sysrole.FieldStatus, field.TypeString, value)
	}
	if value, ok := sru.mutation.Remark(); ok {
		_spec.SetField(sysrole.FieldRemark, field.TypeString, value)
	}
	if sru.mutation.RemarkCleared() {
		_spec.ClearField(sysrole.FieldRemark, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	sru.mutation.done = true
	return n, nil
}

// SysRoleUpdateOne is the builder for updating a single SysRole entity.
type SysRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysRoleMutation
}

// SetCreatedBy sets the "created_by" field.
func (sruo *SysRoleUpdateOne) SetCreatedBy(s string) *SysRoleUpdateOne {
	sruo.mutation.SetCreatedBy(s)
	return sruo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (sruo *SysRoleUpdateOne) SetNillableCreatedBy(s *string) *SysRoleUpdateOne {
	if s != nil {
		sruo.SetCreatedBy(*s)
	}
	return sruo
}

// SetUpdatedBy sets the "updated_by" field.
func (sruo *SysRoleUpdateOne) SetUpdatedBy(s string) *SysRoleUpdateOne {
	sruo.mutation.SetUpdatedBy(s)
	return sruo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (sruo *SysRoleUpdateOne) SetNillableUpdatedBy(s *string) *SysRoleUpdateOne {
	if s != nil {
		sruo.SetUpdatedBy(*s)
	}
	return sruo
}

// SetUpdatedAt sets the "updated_at" field.
func (sruo *SysRoleUpdateOne) SetUpdatedAt(t time.Time) *SysRoleUpdateOne {
	sruo.mutation.SetUpdatedAt(t)
	return sruo
}

// SetDeletedAt sets the "deleted_at" field.
func (sruo *SysRoleUpdateOne) SetDeletedAt(t time.Time) *SysRoleUpdateOne {
	sruo.mutation.SetDeletedAt(t)
	return sruo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sruo *SysRoleUpdateOne) SetNillableDeletedAt(t *time.Time) *SysRoleUpdateOne {
	if t != nil {
		sruo.SetDeletedAt(*t)
	}
	return sruo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (sruo *SysRoleUpdateOne) ClearDeletedAt() *SysRoleUpdateOne {
	sruo.mutation.ClearDeletedAt()
	return sruo
}

// SetName sets the "name" field.
func (sruo *SysRoleUpdateOne) SetName(s string) *SysRoleUpdateOne {
	sruo.mutation.SetName(s)
	return sruo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (sruo *SysRoleUpdateOne) SetNillableName(s *string) *SysRoleUpdateOne {
	if s != nil {
		sruo.SetName(*s)
	}
	return sruo
}

// SetCode sets the "code" field.
func (sruo *SysRoleUpdateOne) SetCode(s string) *SysRoleUpdateOne {
	sruo.mutation.SetCode(s)
	return sruo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (sruo *SysRoleUpdateOne) SetNillableCode(s *string) *SysRoleUpdateOne {
	if s != nil {
		sruo.SetCode(*s)
	}
	return sruo
}

// SetSort sets the "sort" field.
func (sruo *SysRoleUpdateOne) SetSort(i int) *SysRoleUpdateOne {
	sruo.mutation.ResetSort()
	sruo.mutation.SetSort(i)
	return sruo
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (sruo *SysRoleUpdateOne) SetNillableSort(i *int) *SysRoleUpdateOne {
	if i != nil {
		sruo.SetSort(*i)
	}
	return sruo
}

// AddSort adds i to the "sort" field.
func (sruo *SysRoleUpdateOne) AddSort(i int) *SysRoleUpdateOne {
	sruo.mutation.AddSort(i)
	return sruo
}

// SetIsAdmin sets the "is_admin" field.
func (sruo *SysRoleUpdateOne) SetIsAdmin(b bool) *SysRoleUpdateOne {
	sruo.mutation.SetIsAdmin(b)
	return sruo
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (sruo *SysRoleUpdateOne) SetNillableIsAdmin(b *bool) *SysRoleUpdateOne {
	if b != nil {
		sruo.SetIsAdmin(*b)
	}
	return sruo
}

// SetStatus sets the "status" field.
func (sruo *SysRoleUpdateOne) SetStatus(s string) *SysRoleUpdateOne {
	sruo.mutation.SetStatus(s)
	return sruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sruo *SysRoleUpdateOne) SetNillableStatus(s *string) *SysRoleUpdateOne {
	if s != nil {
		sruo.SetStatus(*s)
	}
	return sruo
}

// SetRemark sets the "remark" field.
func (sruo *SysRoleUpdateOne) SetRemark(s string) *SysRoleUpdateOne {
	sruo.mutation.SetRemark(s)
	return sruo
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (sruo *SysRoleUpdateOne) SetNillableRemark(s *string) *SysRoleUpdateOne {
	if s != nil {
		sruo.SetRemark(*s)
	}
	return sruo
}

// ClearRemark clears the value of the "remark" field.
func (sruo *SysRoleUpdateOne) ClearRemark() *SysRoleUpdateOne {
	sruo.mutation.ClearRemark()
	return sruo
}

// Mutation returns the SysRoleMutation object of the builder.
func (sruo *SysRoleUpdateOne) Mutation() *SysRoleMutation {
	return sruo.mutation
}

// Where appends a list predicates to the SysRoleUpdate builder.
func (sruo *SysRoleUpdateOne) Where(ps ...predicate.SysRole) *SysRoleUpdateOne {
	sruo.mutation.Where(ps...)
	return sruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sruo *SysRoleUpdateOne) Select(field string, fields ...string) *SysRoleUpdateOne {
	sruo.fields = append([]string{field}, fields...)
	return sruo
}

// Save executes the query and returns the updated SysRole entity.
func (sruo *SysRoleUpdateOne) Save(ctx context.Context) (*SysRole, error) {
	sruo.defaults()
	return withHooks(ctx, sruo.sqlSave, sruo.mutation, sruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sruo *SysRoleUpdateOne) SaveX(ctx context.Context) *SysRole {
	node, err := sruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sruo *SysRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := sruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sruo *SysRoleUpdateOne) ExecX(ctx context.Context) {
	if err := sruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sruo *SysRoleUpdateOne) defaults() {
	if _, ok := sruo.mutation.UpdatedAt(); !ok {
		v := sysrole.UpdateDefaultUpdatedAt()
		sruo.mutation.SetUpdatedAt(v)
	}
}

func (sruo *SysRoleUpdateOne) sqlSave(ctx context.Context) (_node *SysRole, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysrole.Table, sysrole.Columns, sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64))
	id, ok := sruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysrole.FieldID)
		for _, f := range fields {
			if !sysrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sruo.mutation.CreatedBy(); ok {
		_spec.SetField(sysrole.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := sruo.mutation.UpdatedBy(); ok {
		_spec.SetField(sysrole.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := sruo.mutation.UpdatedAt(); ok {
		_spec.SetField(sysrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := sruo.mutation.DeletedAt(); ok {
		_spec.SetField(sysrole.FieldDeletedAt, field.TypeTime, value)
	}
	if sruo.mutation.DeletedAtCleared() {
		_spec.ClearField(sysrole.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := sruo.mutation.Name(); ok {
		_spec.SetField(sysrole.FieldName, field.TypeString, value)
	}
	if value, ok := sruo.mutation.Code(); ok {
		_spec.SetField(sysrole.FieldCode, field.TypeString, value)
	}
	if value, ok := sruo.mutation.Sort(); ok {
		_spec.SetField(sysrole.FieldSort, field.TypeInt, value)
	}
	if value, ok := sruo.mutation.AddedSort(); ok {
		_spec.AddField(sysrole.FieldSort, field.TypeInt, value)
	}
	if value, ok := sruo.mutation.IsAdmin(); ok {
		_spec.SetField(sysrole.FieldIsAdmin, field.TypeBool, value)
	}
	if value, ok := sruo.mutation.Status(); ok {
		_spec.SetField(sysrole.FieldStatus, field.TypeString, value)
	}
	if value, ok := sruo.mutation.Remark(); ok {
		_spec.SetField(sysrole.FieldRemark, field.TypeString, value)
	}
	if sruo.mutation.RemarkCleared() {
		_spec.ClearField(sysrole.FieldRemark, field.TypeString)
	}
	_node = &SysRole{config: sruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	sruo.mutation.done = true
	return _node, nil
}
