// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gokeep/server/internal/ent/sysuserrole"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysUserRoleCreate is the builder for creating a SysUserRole entity.
type SysUserRoleCreate struct {
	config
	mutation *SysUserRoleMutation
	hooks    []Hook
}

// SetCreatedBy sets the "created_by" field.
func (surc *SysUserRoleCreate) SetCreatedBy(s string) *SysUserRoleCreate {
	surc.mutation.SetCreatedBy(s)
	return surc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (surc *SysUserRoleCreate) SetNillableCreatedBy(s *string) *SysUserRoleCreate {
	if s != nil {
		surc.SetCreatedBy(*s)
	}
	return surc
}

// SetUpdatedBy sets the "updated_by" field.
func (surc *SysUserRoleCreate) SetUpdatedBy(s string) *SysUserRoleCreate {
	surc.mutation.SetUpdatedBy(s)
	return surc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (surc *SysUserRoleCreate) SetNillableUpdatedBy(s *string) *SysUserRoleCreate {
	if s != nil {
		surc.SetUpdatedBy(*s)
	}
	return surc
}

// SetCreatedAt sets the "created_at" field.
func (surc *SysUserRoleCreate) SetCreatedAt(t time.Time) *SysUserRoleCreate {
	surc.mutation.SetCreatedAt(t)
	return surc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (surc *SysUserRoleCreate) SetNillableCreatedAt(t *time.Time) *SysUserRoleCreate {
	if t != nil {
		surc.SetCreatedAt(*t)
	}
	return surc
}

// SetUpdatedAt sets the "updated_at" field.
func (surc *SysUserRoleCreate) SetUpdatedAt(t time.Time) *SysUserRoleCreate {
	surc.mutation.SetUpdatedAt(t)
	return surc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (surc *SysUserRoleCreate) SetNillableUpdatedAt(t *time.Time) *SysUserRoleCreate {
	if t != nil {
		surc.SetUpdatedAt(*t)
	}
	return surc
}

// SetDeletedAt sets the "deleted_at" field.
func (surc *SysUserRoleCreate) SetDeletedAt(t time.Time) *SysUserRoleCreate {
	surc.mutation.SetDeletedAt(t)
	return surc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (surc *SysUserRoleCreate) SetNillableDeletedAt(t *time.Time) *SysUserRoleCreate {
	if t != nil {
		surc.SetDeletedAt(*t)
	}
	return surc
}

// SetUserID sets the "user_id" field.
func (surc *SysUserRoleCreate) SetUserID(i int64) *SysUserRoleCreate {
	surc.mutation.SetUserID(i)
	return surc
}

// SetRoleID sets the "role_id" field.
func (surc *SysUserRoleCreate) SetRoleID(i int64) *SysUserRoleCreate {
	surc.mutation.SetRoleID(i)
	return surc
}

// SetID sets the "id" field.
func (surc *SysUserRoleCreate) SetID(i int64) *SysUserRoleCreate {
	surc.mutation.SetID(i)
	return surc
}

// Mutation returns the SysUserRoleMutation object of the builder.
func (surc *SysUserRoleCreate) Mutation() *SysUserRoleMutation {
	return surc.mutation
}

// Save creates the SysUserRole in the database.
func (surc *SysUserRoleCreate) Save(ctx context.Context) (*SysUserRole, error) {
	surc.defaults()
	return withHooks(ctx, surc.sqlSave, surc.mutation, surc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (surc *SysUserRoleCreate) SaveX(ctx context.Context) *SysUserRole {
	v, err := surc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (surc *SysUserRoleCreate) Exec(ctx context.Context) error {
	_, err := surc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (surc *SysUserRoleCreate) ExecX(ctx context.Context) {
	if err := surc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (surc *SysUserRoleCreate) defaults() {
	if _, ok := surc.mutation.CreatedBy(); !ok {
		v := sysuserrole.DefaultCreatedBy
		surc.mutation.SetCreatedBy(v)
	}
	if _, ok := surc.mutation.UpdatedBy(); !ok {
		v := sysuserrole.DefaultUpdatedBy
		surc.mutation.SetUpdatedBy(v)
	}
	if _, ok := surc.mutation.CreatedAt(); !ok {
		v := sysuserrole.DefaultCreatedAt()
		surc.mutation.SetCreatedAt(v)
	}
	if _, ok := surc.mutation.UpdatedAt(); !ok {
		v := sysuserrole.DefaultUpdatedAt()
		surc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (surc *SysUserRoleCreate) check() error {
	if _, ok := surc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "SysUserRole.created_by"`)}
	}
	if _, ok := surc.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "SysUserRole.updated_by"`)}
	}
	if _, ok := surc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysUserRole.created_at"`)}
	}
	if _, ok := surc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SysUserRole.updated_at"`)}
	}
	if _, ok := surc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SysUserRole.user_id"`)}
	}
	if _, ok := surc.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "SysUserRole.role_id"`)}
	}
	return nil
}

func (surc *SysUserRoleCreate) sqlSave(ctx context.Context) (*SysUserRole, error) {
	if err := surc.check(); err != nil {
		return nil, err
	}
	_node, _spec := surc.createSpec()
	if err := sqlgraph.CreateNode(ctx, surc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	surc.mutation.id = &_node.ID
	surc.mutation.done = true
	return _node, nil
}

func (surc *SysUserRoleCreate) createSpec() (*SysUserRole, *sqlgraph.CreateSpec) {
	var (
		_node = &SysUserRole{config: surc.config}
		_spec = sqlgraph.NewCreateSpec(sysuserrole.Table, sqlgraph.NewFieldSpec(sysuserrole.FieldID, field.TypeInt64))
	)
	if id, ok := surc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := surc.mutation.CreatedBy(); ok {
		_spec.SetField(sysuserrole.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := surc.mutation.UpdatedBy(); ok {
		_spec.SetField(sysuserrole.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := surc.mutation.CreatedAt(); ok {
		_spec.SetField(sysuserrole.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := surc.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuserrole.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := surc.mutation.DeletedAt(); ok {
		_spec.SetField(sysuserrole.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := surc.mutation.UserID(); ok {
		_spec.SetField(sysuserrole.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := surc.mutation.RoleID(); ok {
		_spec.SetField(sysuserrole.FieldRoleID, field.TypeInt64, value)
		_node.RoleID = value
	}
	return _node, _spec
}

// SysUserRoleCreateBulk is the builder for creating many SysUserRole entities in bulk.
type SysUserRoleCreateBulk struct {
	config
	err      error
	builders []*SysUserRoleCreate
}

// Save creates the SysUserRole entities in the database.
func (surcb *SysUserRoleCreateBulk) Save(ctx context.Context) ([]*SysUserRole, error) {
	if surcb.err != nil {
		return nil, surcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(surcb.builders))
	nodes := make([]*SysUserRole, len(surcb.builders))
	mutators := make([]Mutator, len(surcb.builders))
	for i := range surcb.builders {
		func(i int, root context.Context) {
			builder := surcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysUserRoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, surcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, surcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, surcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (surcb *SysUserRoleCreateBulk) SaveX(ctx context.Context) []*SysUserRole {
	v, err := surcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (surcb *SysUserRoleCreateBulk) Exec(ctx context.Context) error {
	_, err := surcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (surcb *SysUserRoleCreateBulk) ExecX(ctx context.Context) {
	if err := surcb.Exec(ctx); err != nil {
		panic(err)
	}
}
