// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gokeep/server/internal/ent/predicate"
	"gokeep/server/internal/ent/sysuser"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysUserUpdate is the builder for updating SysUser entities.
type SysUserUpdate struct {
	config
	hooks    []Hook
	mutation *SysUserMutation
}

// Where appends a list predicates to the SysUserUpdate builder.
func (suu *SysUserUpdate) Where(ps ...predicate.SysUser) *SysUserUpdate {
	suu.mutation.Where(ps...)
	return suu
}

// SetCreatedBy sets the "created_by" field.
func (suu *SysUserUpdate) SetCreatedBy(s string) *SysUserUpdate {
	suu.mutation.SetCreatedBy(s)
	return suu
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (suu *SysUserUpdate) SetNillableCreatedBy(s *string) *SysUserUpdate {
	if s != nil {
		suu.SetCreatedBy(*s)
	}
	return suu
}

// SetUpdatedBy sets the "updated_by" field.
func (suu *SysUserUpdate) SetUpdatedBy(s string) *SysUserUpdate {
	suu.mutation.SetUpdatedBy(s)
	return suu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (suu *SysUserUpdate) SetNillableUpdatedBy(s *string) *SysUserUpdate {
	if s != nil {
		suu.SetUpdatedBy(*s)
	}
	return suu
}

// SetUpdatedAt sets the "updated_at" field.
func (suu *SysUserUpdate) SetUpdatedAt(t time.Time) *SysUserUpdate {
	suu.mutation.SetUpdatedAt(t)
	return suu
}

// SetDeletedAt sets the "deleted_at" field.
func (suu *SysUserUpdate) SetDeletedAt(t time.Time) *SysUserUpdate {
	suu.mutation.SetDeletedAt(t)
	return suu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (suu *SysUserUpdate) SetNillableDeletedAt(t *time.Time) *SysUserUpdate {
	if t != nil {
		suu.SetDeletedAt(*t)
	}
	return suu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (suu *SysUserUpdate) ClearDeletedAt() *SysUserUpdate {
	suu.mutation.ClearDeletedAt()
	return suu
}

// SetUsername sets the "username" field.
func (suu *SysUserUpdate) SetUsername(s string) *SysUserUpdate {
	suu.mutation.SetUsername(s)
	return suu
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (suu *SysUserUpdate) SetNillableUsername(s *string) *SysUserUpdate {
	if s != nil {
		suu.SetUsername(*s)
	}
	return suu
}

// SetPassword sets the "password" field.
func (suu *SysUserUpdate) SetPassword(s string) *SysUserUpdate {
	suu.mutation.SetPassword(s)
	return suu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (suu *SysUserUpdate) SetNillablePassword(s *string) *SysUserUpdate {
	if s != nil {
		suu.SetPassword(*s)
	}
	return suu
}

// SetNickname sets the "nickname" field.
func (suu *SysUserUpdate) SetNickname(s string) *SysUserUpdate {
	suu.mutation.SetNickname(s)
	return suu
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (suu *SysUserUpdate) SetNillableNickname(s *string) *SysUserUpdate {
	if s != nil {
		suu.SetNickname(*s)
	}
	return suu
}

// SetPhone sets the "phone" field.
func (suu *SysUserUpdate) SetPhone(s string) *SysUserUpdate {
	suu.mutation.SetPhone(s)
	return suu
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (suu *SysUserUpdate) SetNillablePhone(s *string) *SysUserUpdate {
	if s != nil {
		suu.SetPhone(*s)
	}
	return suu
}

// ClearPhone clears the value of the "phone" field.
func (suu *SysUserUpdate) ClearPhone() *SysUserUpdate {
	suu.mutation.ClearPhone()
	return suu
}

// SetEmail sets the "email" field.
func (suu *SysUserUpdate) SetEmail(s string) *SysUserUpdate {
	suu.mutation.SetEmail(s)
	return suu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (suu *SysUserUpdate) SetNillableEmail(s *string) *SysUserUpdate {
	if s != nil {
		suu.SetEmail(*s)
	}
	return suu
}

// ClearEmail clears the value of the "email" field.
func (suu *SysUserUpdate) ClearEmail() *SysUserUpdate {
	suu.mutation.ClearEmail()
	return suu
}

// SetStatus sets the "status" field.
func (suu *SysUserUpdate) SetStatus(s string) *SysUserUpdate {
	suu.mutation.SetStatus(s)
	return suu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (suu *SysUserUpdate) SetNillableStatus(s *string) *SysUserUpdate {
	if s != nil {
		suu.SetStatus(*s)
	}
	return suu
}

// SetRemark sets the "remark" field.
func (suu *SysUserUpdate) SetRemark(s string) *SysUserUpdate {
	suu.mutation.SetRemark(s)
	return suu
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (suu *SysUserUpdate) SetNillableRemark(s *string) *SysUserUpdate {
	if s != nil {
		suu.SetRemark(*s)
	}
	return suu
}

// ClearRemark clears the value of the "remark" field.
func (suu *SysUserUpdate) ClearRemark() *SysUserUpdate {
	suu.mutation.ClearRemark()
	return suu
}

// Mutation returns the SysUserMutation object of the builder.
func (suu *SysUserUpdate) Mutation() *SysUserMutation {
	return suu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (suu *SysUserUpdate) Save(ctx context.Context) (int, error) {
	suu.defaults()
	return withHooks(ctx, suu.sqlSave, suu.mutation, suu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suu *SysUserUpdate) SaveX(ctx context.Context) int {
	affected, err := suu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (suu *SysUserUpdate) Exec(ctx context.Context) error {
	_, err := suu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suu *SysUserUpdate) ExecX(ctx context.Context) {
	if err := suu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suu *SysUserUpdate) defaults() {
	if _, ok := suu.mutation.UpdatedAt(); !ok {
		v := sysuser.UpdateDefaultUpdatedAt()
		suu.mutation.SetUpdatedAt(v)
	}
}

func (suu *SysUserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysuser.Table, sysuser.Columns, sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeInt64))
	if ps := suu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suu.mutation.CreatedBy(); ok {
		_spec.SetField(sysuser.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := suu.mutation.UpdatedBy(); ok {
		_spec.SetField(sysuser.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := suu.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := suu.mutation.DeletedAt(); ok {
		_spec.SetField(sysuser.FieldDeletedAt, field.TypeTime, value)
	}
	if suu.mutation.DeletedAtCleared() {
		_spec.ClearField(sysuser.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := suu.mutation.Username(); ok {
		_spec.SetField(sysuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := suu.mutation.Password(); ok {
		_spec.SetField(sysuser.FieldPassword, field.TypeString, value)
	}
	if value, ok := suu.mutation.Nickname(); ok {
		_spec.SetField(sysuser.FieldNickname, field.TypeString, value)
	}
	if value, ok := suu.mutation.Phone(); ok {
		_spec.SetField(sysuser.FieldPhone, field.TypeString, value)
	}
	if suu.mutation.PhoneCleared() {
		_spec.ClearField(sysuser.FieldPhone, field.TypeString)
	}
	if value, ok := suu.mutation.Email(); ok {
		_spec.SetField(sysuser.FieldEmail, field.TypeString, value)
	}
	if suu.mutation.EmailCleared() {
		_spec.ClearField(sysuser.FieldEmail, field.TypeString)
	}
	if value, ok := suu.mutation.Status(); ok {
		_spec.SetField(sysuser.FieldStatus, field.TypeString, value)
	}
	if value, ok := suu.mutation.Remark(); ok {
		_spec.SetField(sysuser.FieldRemark, field.TypeString, value)
	}
	if suu.mutation.RemarkCleared() {
		_spec.ClearField(sysuser.FieldRemark, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, suu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	suu.mutation.done = true
	return n, nil
}

// SysUserUpdateOne is the builder for updating a single SysUser entity.
type SysUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysUserMutation
}

// SetCreatedBy sets the "created_by" field.
func (suuo *SysUserUpdateOne) SetCreatedBy(s string) *SysUserUpdateOne {
	suuo.mutation.SetCreatedBy(s)
	return suuo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (suuo *SysUserUpdateOne) SetNillableCreatedBy(s *string) *SysUserUpdateOne {
	if s != nil {
		suuo.SetCreatedBy(*s)
	}
	return suuo
}

// SetUpdatedBy sets the "updated_by" field.
func (suuo *SysUserUpdateOne) SetUpdatedBy(s string) *SysUserUpdateOne {
	suuo.mutation.SetUpdatedBy(s)
	return suuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (suuo *SysUserUpdateOne) SetNillableUpdatedBy(s *string) *SysUserUpdateOne {
	if s != nil {
		suuo.SetUpdatedBy(*s)
	}
	return suuo
}

// SetUpdatedAt sets the "updated_at" field.
func (suuo *SysUserUpdateOne) SetUpdatedAt(t time.Time) *SysUserUpdateOne {
	suuo.mutation.SetUpdatedAt(t)
	return suuo
}

// SetDeletedAt sets the "deleted_at" field.
func (suuo *SysUserUpdateOne) SetDeletedAt(t time.Time) *SysUserUpdateOne {
	suuo.mutation.SetDeletedAt(t)
	return suuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (suuo *SysUserUpdateOne) SetNillableDeletedAt(t *time.Time) *SysUserUpdateOne {
	if t != nil {
		suuo.SetDeletedAt(*t)
	}
	return suuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (suuo *SysUserUpdateOne) ClearDeletedAt() *SysUserUpdateOne {
	suuo.mutation.ClearDeletedAt()
	return suuo
}

// SetUsername sets the "username" field.
func (suuo *SysUserUpdateOne) SetUsername(s string) *SysUserUpdateOne {
	suuo.mutation.SetUsername(s)
	return suuo
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (suuo *SysUserUpdateOne) SetNillableUsername(s *string) *SysUserUpdateOne {
	if s != nil {
		suuo.SetUsername(*s)
	}
	return suuo
}

// SetPassword sets the "password" field.
func (suuo *SysUserUpdateOne) SetPassword(s string) *SysUserUpdateOne {
	suuo.mutation.SetPassword(s)
	return suuo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (suuo *SysUserUpdateOne) SetNillablePassword(s *string) *SysUserUpdateOne {
	if s != nil {
		suuo.SetPassword(*s)
	}
	return suuo
}

// SetNickname sets the "nickname" field.
func (suuo *SysUserUpdateOne) SetNickname(s string) *SysUserUpdateOne {
	suuo.mutation.SetNickname(s)
	return suuo
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (suuo *SysUserUpdateOne) SetNillableNickname(s *string) *SysUserUpdateOne {
	if s != nil {
		suuo.SetNickname(*s)
	}
	return suuo
}

// SetPhone sets the "phone" field.
func (suuo *SysUserUpdateOne) SetPhone(s string) *SysUserUpdateOne {
	suuo.mutation.SetPhone(s)
	return suuo
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (suuo *SysUserUpdateOne) SetNillablePhone(s *string) *SysUserUpdateOne {
	if s != nil {
		suuo.SetPhone(*s)
	}
	return suuo
}

// ClearPhone clears the value of the "phone" field.
func (suuo *SysUserUpdateOne) ClearPhone() *SysUserUpdateOne {
	suuo.mutation.ClearPhone()
	return suuo
}

// SetEmail sets the "email" field.
func (suuo *SysUserUpdateOne) SetEmail(s string) *SysUserUpdateOne {
	suuo.mutation.SetEmail(s)
	return suuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (suuo *SysUserUpdateOne) SetNillableEmail(s *string) *SysUserUpdateOne {
	if s != nil {
		suuo.SetEmail(*s)
	}
	return suuo
}

// ClearEmail clears the value of the "email" field.
func (suuo *SysUserUpdateOne) ClearEmail() *SysUserUpdateOne {
	suuo.mutation.ClearEmail()
	return suuo
}

// SetStatus sets the "status" field.
func (suuo *SysUserUpdateOne) SetStatus(s string) *SysUserUpdateOne {
	suuo.mutation.SetStatus(s)
	return suuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (suuo *SysUserUpdateOne) SetNillableStatus(s *string) *SysUserUpdateOne {
	if s != nil {
		suuo.SetStatus(*s)
	}
	return suuo
}

// SetRemark sets the "remark" field.
func (suuo *SysUserUpdateOne) SetRemark(s string) *SysUserUpdateOne {
	suuo.mutation.SetRemark(s)
	return suuo
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (suuo *SysUserUpdateOne) SetNillableRemark(s *string) *SysUserUpdateOne {
	if s != nil {
		suuo.SetRemark(*s)
	}
	return suuo
}

// ClearRemark clears the value of the "remark" field.
func (suuo *SysUserUpdateOne) ClearRemark() *SysUserUpdateOne {
	suuo.mutation.ClearRemark()
	return suuo
}

// Mutation returns the SysUserMutation object of the builder.
func (suuo *SysUserUpdateOne) Mutation() *SysUserMutation {
	return suuo.mutation
}

// Where appends a list predicates to the SysUserUpdate builder.
func (suuo *SysUserUpdateOne) Where(ps ...predicate.SysUser) *SysUserUpdateOne {
	suuo.mutation.Where(ps...)
	return suuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suuo *SysUserUpdateOne) Select(field string, fields ...string) *SysUserUpdateOne {
	suuo.fields = append([]string{field}, fields...)
	return suuo
}

// Save executes the query and returns the updated SysUser entity.
func (suuo *SysUserUpdateOne) Save(ctx context.Context) (*SysUser, error) {
	suuo.defaults()
	return withHooks(ctx, suuo.sqlSave, suuo.mutation, suuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suuo *SysUserUpdateOne) SaveX(ctx context.Context) *SysUser {
	node, err := suuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suuo *SysUserUpdateOne) Exec(ctx context.Context) error {
	_, err := suuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suuo *SysUserUpdateOne) ExecX(ctx context.Context) {
	if err := suuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suuo *SysUserUpdateOne) defaults() {
	if _, ok := suuo.mutation.UpdatedAt(); !ok {
		v := sysuser.UpdateDefaultUpdatedAt()
		suuo.mutation.SetUpdatedAt(v)
	}
}

func (suuo *SysUserUpdateOne) sqlSave(ctx context.Context) (_node *SysUser, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysuser.Table, sysuser.Columns, sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeInt64))
	id, ok := suuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysuser.FieldID)
		for _, f := range fields {
			if !sysuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suuo.mutation.CreatedBy(); ok {
		_spec.SetField(sysuser.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := suuo.mutation.UpdatedBy(); ok {
		_spec.SetField(sysuser.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := suuo.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := suuo.mutation.DeletedAt(); ok {
		_spec.SetField(sysuser.FieldDeletedAt, field.TypeTime, value)
	}
	if suuo.mutation.DeletedAtCleared() {
		_spec.ClearField(sysuser.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := suuo.mutation.Username(); ok {
		_spec.SetField(sysuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := suuo.mutation.Password(); ok {
		_spec.SetField(sysuser.FieldPassword, field.TypeString, value)
	}
	if value, ok := suuo.mutation.Nickname(); ok {
		_spec.SetField(sysuser.FieldNickname, field.TypeString, value)
	}
	if value, ok := suuo.mutation.Phone(); ok {
		_spec.SetField(sysuser.FieldPhone, field.TypeString, value)
	}
	if suuo.mutation.PhoneCleared() {
		_spec.ClearField(sysuser.FieldPhone, field.TypeString)
	}
	if value, ok := suuo.mutation.Email(); ok {
		_spec.SetField(sysuser.FieldEmail, field.TypeString, value)
	}
	if suuo.mutation.EmailCleared() {
		_spec.ClearField(sysuser.FieldEmail, field.TypeString)
	}
	if value, ok := suuo.mutation.Status(); ok {
		_spec.SetField(sysuser.FieldStatus, field.TypeString, value)
	}
	if value, ok := suuo.mutation.Remark(); ok {
		_spec.SetField(sysuser.FieldRemark, field.TypeString, value)
	}
	if suuo.mutation.RemarkCleared() {
		_spec.ClearField(sysuser.FieldRemark, field.TypeString)
	}
	_node = &SysUser{config: suuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suuo.mutation.done = true
	return _node, nil
}
