// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gokeep/server/internal/ent/predicate"
	"gokeep/server/internal/ent/sysuserrole"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysUserRoleUpdate is the builder for updating SysUserRole entities.
type SysUserRoleUpdate struct {
	config
	hooks    []Hook
	mutation *SysUserRoleMutation
}

// Where appends a list predicates to the SysUserRoleUpdate builder.
func (suru *SysUserRoleUpdate) Where(ps ...predicate.SysUserRole) *SysUserRoleUpdate {
	suru.mutation.Where(ps...)
	return suru
}

// SetCreatedBy sets the "created_by" field.
func (suru *SysUserRoleUpdate) SetCreatedBy(s string) *SysUserRoleUpdate {
	suru.mutation.SetCreatedBy(s)
	return suru
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (suru *SysUserRoleUpdate) SetNillableCreatedBy(s *string) *SysUserRoleUpdate {
	if s != nil {
		suru.SetCreatedBy(*s)
	}
	return suru
}

// SetUpdatedBy sets the "updated_by" field.
func (suru *SysUserRoleUpdate) SetUpdatedBy(s string) *SysUserRoleUpdate {
	suru.mutation.SetUpdatedBy(s)
	return suru
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (suru *SysUserRoleUpdate) SetNillableUpdatedBy(s *string) *SysUserRoleUpdate {
	if s != nil {
		suru.SetUpdatedBy(*s)
	}
	return suru
}

// SetUpdatedAt sets the "updated_at" field.
func (suru *SysUserRoleUpdate) SetUpdatedAt(t time.Time) *SysUserRoleUpdate {
	suru.mutation.SetUpdatedAt(t)
	return suru
}

// SetDeletedAt sets the "deleted_at" field.
func (suru *SysUserRoleUpdate) SetDeletedAt(t time.Time) *SysUserRoleUpdate {
	suru.mutation.SetDeletedAt(t)
	return suru
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (suru *SysUserRoleUpdate) SetNillableDeletedAt(t *time.Time) *SysUserRoleUpdate {
	if t != nil {
		suru.SetDeletedAt(*t)
	}
	return suru
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (suru *SysUserRoleUpdate) ClearDeletedAt() *SysUserRoleUpdate {
	suru.mutation.ClearDeletedAt()
	return suru
}

// SetUserID sets the "user_id" field.
func (suru *SysUserRoleUpdate) SetUserID(i int64) *SysUserRoleUpdate {
	suru.mutation.ResetUserID()
	suru.mutation.SetUserID(i)
	return suru
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (suru *SysUserRoleUpdate) SetNillableUserID(i *int64) *SysUserRoleUpdate {
	if i != nil {
		suru.SetUserID(*i)
	}
	return suru
}

// AddUserID adds i to the "user_id" field.
func (suru *SysUserRoleUpdate) AddUserID(i int64) *SysUserRoleUpdate {
	suru.mutation.AddUserID(i)
	return suru
}

// SetRoleID sets the "role_id" field.
func (suru *SysUserRoleUpdate) SetRoleID(i int64) *SysUserRoleUpdate {
	suru.mutation.ResetRoleID()
	suru.mutation.SetRoleID(i)
	return suru
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (suru *SysUserRoleUpdate) SetNillableRoleID(i *int64) *SysUserRoleUpdate {
	if i != nil {
		suru.SetRoleID(*i)
	}
	return suru
}

// AddRoleID adds i to the "role_id" field.
func (suru *SysUserRoleUpdate) AddRoleID(i int64) *SysUserRoleUpdate {
	suru.mutation.AddRoleID(i)
	return suru
}

// Mutation returns the SysUserRoleMutation object of the builder.
func (suru *SysUserRoleUpdate) Mutation() *SysUserRoleMutation {
	return suru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (suru *SysUserRoleUpdate) Save(ctx context.Context) (int, error) {
	suru.defaults()
	return withHooks(ctx, suru.sqlSave, suru.mutation, suru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suru *SysUserRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := suru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (suru *SysUserRoleUpdate) Exec(ctx context.Context) error {
	_, err := suru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suru *SysUserRoleUpdate) ExecX(ctx context.Context) {
	if err := suru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suru *SysUserRoleUpdate) defaults() {
	if _, ok := suru.mutation.UpdatedAt(); !ok {
		v := sysuserrole.UpdateDefaultUpdatedAt()
		suru.mutation.SetUpdatedAt(v)
	}
}

func (suru *SysUserRoleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysuserrole.Table, sysuserrole.Columns, sqlgraph.NewFieldSpec(sysuserrole.FieldID, field.TypeInt64))
	if ps := suru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suru.mutation.CreatedBy(); ok {
		_spec.SetField(sysuserrole.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := suru.mutation.UpdatedBy(); ok {
		_spec.SetField(sysuserrole.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := suru.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuserrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := suru.mutation.DeletedAt(); ok {
		_spec.SetField(sysuserrole.FieldDeletedAt, field.TypeTime, value)
	}
	if suru.mutation.DeletedAtCleared() {
		_spec.ClearField(sysuserrole.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := suru.mutation.UserID(); ok {
		_spec.SetField(sysuserrole.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := suru.mutation.AddedUserID(); ok {
		_spec.AddField(sysuserrole.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := suru.mutation.RoleID(); ok {
		_spec.SetField(sysuserrole.FieldRoleID, field.TypeInt64, value)
	}
	if value, ok := suru.mutation.AddedRoleID(); ok {
		_spec.AddField(sysuserrole.FieldRoleID, field.TypeInt64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, suru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysuserrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	suru.mutation.done = true
	return n, nil
}

// SysUserRoleUpdateOne is the builder for updating a single SysUserRole entity.
type SysUserRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysUserRoleMutation
}

// SetCreatedBy sets the "created_by" field.
func (suruo *SysUserRoleUpdateOne) SetCreatedBy(s string) *SysUserRoleUpdateOne {
	suruo.mutation.SetCreatedBy(s)
	return suruo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (suruo *SysUserRoleUpdateOne) SetNillableCreatedBy(s *string) *SysUserRoleUpdateOne {
	if s != nil {
		suruo.SetCreatedBy(*s)
	}
	return suruo
}

// SetUpdatedBy sets the "updated_by" field.
func (suruo *SysUserRoleUpdateOne) SetUpdatedBy(s string) *SysUserRoleUpdateOne {
	suruo.mutation.SetUpdatedBy(s)
	return suruo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (suruo *SysUserRoleUpdateOne) SetNillableUpdatedBy(s *string) *SysUserRoleUpdateOne {
	if s != nil {
		suruo.SetUpdatedBy(*s)
	}
	return suruo
}

// SetUpdatedAt sets the "updated_at" field.
func (suruo *SysUserRoleUpdateOne) SetUpdatedAt(t time.Time) *SysUserRoleUpdateOne {
	suruo.mutation.SetUpdatedAt(t)
	return suruo
}

// SetDeletedAt sets the "deleted_at" field.
func (suruo *SysUserRoleUpdateOne) SetDeletedAt(t time.Time) *SysUserRoleUpdateOne {
	suruo.mutation.SetDeletedAt(t)
	return suruo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (suruo *SysUserRoleUpdateOne) SetNillableDeletedAt(t *time.Time) *SysUserRoleUpdateOne {
	if t != nil {
		suruo.SetDeletedAt(*t)
	}
	return suruo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (suruo *SysUserRoleUpdateOne) ClearDeletedAt() *SysUserRoleUpdateOne {
	suruo.mutation.ClearDeletedAt()
	return suruo
}

// SetUserID sets the "user_id" field.
func (suruo *SysUserRoleUpdateOne) SetUserID(i int64) *SysUserRoleUpdateOne {
	suruo.mutation.ResetUserID()
	suruo.mutation.SetUserID(i)
	return suruo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (suruo *SysUserRoleUpdateOne) SetNillableUserID(i *int64) *SysUserRoleUpdateOne {
	if i != nil {
		suruo.SetUserID(*i)
	}
	return suruo
}

// AddUserID adds i to the "user_id" field.
func (suruo *SysUserRoleUpdateOne) AddUserID(i int64) *SysUserRoleUpdateOne {
	suruo.mutation.AddUserID(i)
	return suruo
}

// SetRoleID sets the "role_id" field.
func (suruo *SysUserRoleUpdateOne) SetRoleID(i int64) *SysUserRoleUpdateOne {
	suruo.mutation.ResetRoleID()
	suruo.mutation.SetRoleID(i)
	return suruo
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (suruo *SysUserRoleUpdateOne) SetNillableRoleID(i *int64) *SysUserRoleUpdateOne {
	if i != nil {
		suruo.SetRoleID(*i)
	}
	return suruo
}

// AddRoleID adds i to the "role_id" field.
func (suruo *SysUserRoleUpdateOne) AddRoleID(i int64) *SysUserRoleUpdateOne {
	suruo.mutation.AddRoleID(i)
	return suruo
}

// Mutation returns the SysUserRoleMutation object of the builder.
func (suruo *SysUserRoleUpdateOne) Mutation() *SysUserRoleMutation {
	return suruo.mutation
}

// Where appends a list predicates to the SysUserRoleUpdate builder.
func (suruo *SysUserRoleUpdateOne) Where(ps ...predicate.SysUserRole) *SysUserRoleUpdateOne {
	suruo.mutation.Where(ps...)
	return suruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suruo *SysUserRoleUpdateOne) Select(field string, fields ...string) *SysUserRoleUpdateOne {
	suruo.fields = append([]string{field}, fields...)
	return suruo
}

// Save executes the query and returns the updated SysUserRole entity.
func (suruo *SysUserRoleUpdateOne) Save(ctx context.Context) (*SysUserRole, error) {
	suruo.defaults()
	return withHooks(ctx, suruo.sqlSave, suruo.mutation, suruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suruo *SysUserRoleUpdateOne) SaveX(ctx context.Context) *SysUserRole {
	node, err := suruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suruo *SysUserRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := suruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suruo *SysUserRoleUpdateOne) ExecX(ctx context.Context) {
	if err := suruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suruo *SysUserRoleUpdateOne) defaults() {
	if _, ok := suruo.mutation.UpdatedAt(); !ok {
		v := sysuserrole.UpdateDefaultUpdatedAt()
		suruo.mutation.SetUpdatedAt(v)
	}
}

func (suruo *SysUserRoleUpdateOne) sqlSave(ctx context.Context) (_node *SysUserRole, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysuserrole.Table, sysuserrole.Columns, sqlgraph.NewFieldSpec(sysuserrole.FieldID, field.TypeInt64))
	id, ok := suruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysUserRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysuserrole.FieldID)
		for _, f := range fields {
			if !sysuserrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysuserrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suruo.mutation.CreatedBy(); ok {
		_spec.SetField(sysuserrole.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := suruo.mutation.UpdatedBy(); ok {
		_spec.SetField(sysuserrole.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := suruo.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuserrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := suruo.mutation.DeletedAt(); ok {
		_spec.SetField(sysuserrole.FieldDeletedAt, field.TypeTime, value)
	}
	if suruo.mutation.DeletedAtCleared() {
		_spec.ClearField(sysuserrole.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := suruo.mutation.UserID(); ok {
		_spec.SetField(sysuserrole.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := suruo.mutation.AddedUserID(); ok {
		_spec.AddField(sysuserrole.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := suruo.mutation.RoleID(); ok {
		_spec.SetField(sysuserrole.FieldRoleID, field.TypeInt64, value)
	}
	if value, ok := suruo.mutation.AddedRoleID(); ok {
		_spec.AddField(sysuserrole.FieldRoleID, field.TypeInt64, value)
	}
	_node = &SysUserRole{config: suruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysuserrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suruo.mutation.done = true
	return _node, nil
}
