// 全库逻辑备份：把 public schema 下所有表导出为可执行的 INSERT SQL（gzip 压缩）
package backup

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"strconv"
	"strings"
	"time"
)

// execer 兼容 *sql.DB 与 *sql.Tx
type execer interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
}

// DumpDatabase 导出全库为 SQL 文本（写入 w，不压缩；调用方负责压缩/关闭）
func DumpDatabase(ctx context.Context, db *sql.DB, w io.Writer) error {
	if _, err := io.WriteString(w, "-- GoKeep full database dump\n-- generated by gokeep-server\n\n"); err != nil {
		return err
	}

	rows, err := db.QueryContext(ctx, `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE' ORDER BY table_name`)
	if err != nil {
		return fmt.Errorf("读取表清单失败: %w", err)
	}
	var tables []string
	for rows.Next() {
		var t string
		if err := rows.Scan(&t); err != nil {
			rows.Close()
			return err
		}
		tables = append(tables, t)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return err
	}

	for _, table := range tables {
		if err := dumpTable(ctx, db, w, table); err != nil {
			return fmt.Errorf("导出表 %s 失败: %w", table, err)
		}
	}
	return nil
}

// TruncateAll 清空全部表（恢复前执行）
func TruncateAll(ctx context.Context, db execer) error {
	rows, err := db.QueryContext(ctx, `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'`)
	if err != nil {
		return err
	}
	var tables []string
	for rows.Next() {
		var t string
		if err := rows.Scan(&t); err != nil {
			rows.Close()
			return err
		}
		tables = append(tables, t)
	}
	rows.Close()
	if len(tables) == 0 {
		return nil
	}
	names := make([]string, 0, len(tables))
	for _, t := range tables {
		names = append(names, `"`+t+`"`)
	}
	_, err = db.ExecContext(ctx, "TRUNCATE TABLE "+strings.Join(names, ", ")+" CASCADE")
	return err
}

// RestoreSQL 逐条执行备份 SQL（语句以 ; 结尾；引号感知拆分，避免字段内换行误切）
func RestoreSQL(ctx context.Context, db execer, sqlText string) error {
	for _, stmt := range splitStatements(sqlText) {
		clean, ok := stripCommentLines(stmt)
		if !ok {
			continue
		}
		if _, err := db.ExecContext(ctx, clean); err != nil {
			return fmt.Errorf("执行恢复语句失败: %w\n语句: %.120s...", err, clean)
		}
	}
	return nil
}

// stripCommentLines 去掉语句内的注释行与空行，返回实际 SQL；无实际 SQL 时 ok=false
// （splitStatements 会把 "-- table: xxx" 注释与后续第一条 INSERT 合并为一条，
// 直接按整条判断 "--" 前缀会误删首行数据，因此必须逐行剥离注释）
func stripCommentLines(stmt string) (string, bool) {
	lines := strings.Split(stmt, "\n")
	out := make([]string, 0, len(lines))
	for _, ln := range lines {
		trimmed := strings.TrimSpace(ln)
		if trimmed == "" || strings.HasPrefix(trimmed, "--") {
			continue
		}
		out = append(out, ln)
	}
	clean := strings.TrimSpace(strings.Join(out, "\n"))
	return clean, clean != ""
}

// splitStatements 按分号切分 SQL，跳过单引号字符串内的分号（含 '' 转义）
func splitStatements(text string) []string {
	var out []string
	var cur strings.Builder
	inQuote := false
	runes := []rune(text)
	for i := 0; i < len(runes); i++ {
		ch := runes[i]
		if ch == '\'' {
			if inQuote && i+1 < len(runes) && runes[i+1] == '\'' {
				cur.WriteRune(ch)
				cur.WriteRune(runes[i+1])
				i++
				continue
			}
			inQuote = !inQuote
		}
		if ch == ';' && !inQuote {
			out = append(out, cur.String())
			cur.Reset()
			continue
		}
		cur.WriteRune(ch)
	}
	if strings.TrimSpace(cur.String()) != "" {
		out = append(out, cur.String())
	}
	return out
}

func dumpTable(ctx context.Context, db *sql.DB, w io.Writer, table string) error {
	r, err := db.QueryContext(ctx, `SELECT * FROM "`+table+`"`)
	if err != nil {
		return err
	}
	defer r.Close()

	if _, err := io.WriteString(w, "\n-- table: "+table+"\n"); err != nil {
		return err
	}
	cols, err := r.Columns()
	if err != nil {
		return err
	}
	for r.Next() {
		vals := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := r.Scan(ptrs...); err != nil {
			return err
		}
		parts := make([]string, 0, len(vals))
		for _, v := range vals {
			parts = append(parts, sqlLiteral(v))
		}
		line := "INSERT INTO \"" + table + "\" VALUES (" + strings.Join(parts, ", ") + ");\n"
		if _, err := io.WriteString(w, line); err != nil {
			return err
		}
	}
	return r.Err()
}

// sqlLiteral 把数据库值转成 SQL 字面量
func sqlLiteral(v any) string {
	switch x := v.(type) {
	case nil:
		return "NULL"
	case bool:
		if x {
			return "TRUE"
		}
		return "FALSE"
	case int64:
		return strconv.FormatInt(x, 10)
	case int:
		return strconv.Itoa(x)
	case int32:
		return strconv.FormatInt(int64(x), 10)
	case float64:
		return strconv.FormatFloat(x, 'f', -1, 64)
	case float32:
		return strconv.FormatFloat(float64(x), 'f', -1, 32)
	case time.Time:
		return "'" + x.Format("2006-01-02 15:04:05.999999-07") + "'"
	case []byte:
		// pgx 对 json/jsonb 返回 []byte（原始 JSON），按字符串字面量插入（隐式转 jsonb）
		return "'" + strings.ReplaceAll(string(x), "'", "''") + "'"
	case string:
		return "'" + strings.ReplaceAll(x, "'", "''") + "'"
	default:
		return "'" + strings.ReplaceAll(fmt.Sprintf("%v", x), "'", "''") + "'"
	}
}
